import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import pg from 'pg';
import jwt from 'jsonwebtoken';
const secret='identity-ci-only-secret',origin='http://127.0.0.1:3011';
const pool=new pg.Pool({host:process.env.SQL_HOST,port:Number(process.env.SQL_PORT || 5432),user:process.env.SQL_USER,password:process.env.SQL_PASSWORD,database:process.env.SQL_DB_NAME});
const child=spawn(process.execPath,['dist/server.cjs'],{env:{...process.env,NODE_ENV:'production',JWT_SECRET:secret,BACKUP_ENABLED:'false'},stdio:'inherit'});
const headers={Authorization:'Bearer '+jwt.sign({role:'superadmin',companyId:'default'},secret,{expiresIn:'1h'}),'Content-Type':'application/json'};
const send=(url:string,body:any,auth:Record<string,string>=headers,method='POST')=>fetch(origin+url,{method,headers:auth,body:JSON.stringify(body)});
const tenantHeaders=(companyId:string)=>({...headers,Authorization:'Bearer '+jwt.sign({role:'admin',companyId},secret,{expiresIn:'1h'})});
const create=async(id:string,username:string,email=id+'@example.com')=>{const response=await send('/api/company-registration',{id,name:id,adminUsername:username,adminEmail:email,adminPassword:'company-password',privacyAccepted:true},{'Content-Type':'application/json'});if(response.ok)assert.equal((await send('/api/companies',{id,subscriptionStatus:'active'})).status,200);return response;};
const main=(companyId:string)=>fetch(origin+'/api/main-data?companyId='+companyId,{headers:tenantHeaders(companyId)}).then(r=>r.json()) as Promise<any>;
const save=(companyId:string,data:any)=>send('/api/main-data?companyId='+companyId,{...data,_baseVersion:data._version},tenantHeaders(companyId));
try{
 let ready=false;for(let i=0;i<60;i++){try{if((await fetch(origin+'/api/health/live')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,500));}assert.ok(ready);
 assert.deepEqual(await (await fetch(origin+'/api/companies')).json(),[]);
 const list:any=await (await fetch(origin+'/api/companies',{headers})).json();assert.equal(list.find((c:any)=>c.id==='default').companyCode,'101');assert.ok(list.every((c:any)=>c.adminPassword===undefined));
 const created=await Promise.all([create('identity-a','identity-master-a','master-a@example.com'),create('identity-b','identity-master-b')]);assert.deepEqual(created.map(r=>r.status),[200,200]);const codes=await Promise.all(created.map(r=>r.json())) as any[];const a={...codes[0],id:'identity-a'},b={...codes[1],id:'identity-b'};assert.ok(Number(a.companyCode)>=102);assert.equal(Math.abs(Number(a.companyCode)-Number(b.companyCode)),1);assert.notEqual(a.companyCode,'777');
 assert.equal((await create('identity-c',' IDENTITY-MASTER-A ')).status,409);assert.equal((await create('default','replacement')).status,400);
 const employee={id:'identity-employee-a',name:'Identical display name',username:'identity-user-a',email:'employee-a@example.com',password:'employee-password',dept:''};let da=await main(a.id),db=await main(b.id);da.employees=[employee];assert.equal((await save(a.id,da)).status,200);
 db.employees=[{...employee,id:'identity-employee-b',username:' IDENTITY-USER-A ',email:'employee-b@example.com'}];assert.equal((await save(b.id,db)).status,409);assert.equal((await main(b.id)).employees.length,0);
 db.employees=[{...db.employees[0],username:'identity-user-b',email:' EMPLOYEE-A@EXAMPLE.COM '}];assert.equal((await save(b.id,db)).status,409);db.employees[0].email='employee-b@example.com';assert.equal((await save(b.id,db)).status,200);
 for(const username of [' IDENTITY-USER-A ','EMPLOYEE-A@EXAMPLE.COM']){const response=await send('/api/auth/employee-login',{username,password:'employee-password',companyId:b.id},{'Content-Type':'application/json'});assert.equal(response.status,200);const login:any=await response.json();assert.equal(login.companyId,a.id);assert.equal(login.password,undefined);assert.equal(login.webauthnCredentials,undefined);const claims:any=jwt.verify(login.token,secret);assert.equal(claims.companyId,a.id);assert.equal((await fetch(origin+'/api/main-data?companyId='+b.id,{headers:{Authorization:'Bearer '+login.token}})).status,403);}
 const master:any=await (await send('/api/auth/admin-login',{username:' MASTER-A@EXAMPLE.COM ',password:'company-password'},{'Content-Type':'application/json'})).json();assert.equal(master.companyId,a.id);
 const permissions={canEditSchedule:true,canManageEmployees:true,canManageDepts:true,canApproveRequests:true,canViewReports:true,canManageSettings:true,canPrint:true};
 const sub=await send('/api/admins',{companyId:a.id,name:'Sub admin',username:'identity-sub',email:'identity-sub@example.com',password:'sub-password',permissions,departmentIds:null},tenantHeaders(a.id));assert.equal(sub.status,200);
 assert.equal((await send('/api/admins',{companyId:b.id,name:'Other',username:'identity-sub2',email:'EMPLOYEE-A@EXAMPLE.COM',password:'sub-password',permissions,departmentIds:null},tenantHeaders(b.id))).status,409);
 const subLogin:any=await (await send('/api/auth/admin-login',{username:' IDENTITY-SUB@EXAMPLE.COM ',password:'sub-password'},{'Content-Type':'application/json'})).json();assert.equal(subLogin.companyId,a.id);
 const empLogin:any=await (await send('/api/auth/employee-login',{username:employee.username,password:employee.password},{'Content-Type':'application/json'})).json();assert.equal((await send('/api/employee-profile/email?companyId='+a.id,{email:'employee-b@example.com'},{Authorization:'Bearer '+empLogin.token,'Content-Type':'application/json'},'PATCH')).status,409);
 // Competing company saves for a new login identity must have exactly one winner.
 da=await main(a.id);db=await main(b.id);da.employees.push({...employee,id:'race-a',username:'identity-race',email:'race-a@example.com'});db.employees.push({...employee,id:'race-b',username:'identity-race',email:'race-b@example.com'});const race=await Promise.all([save(a.id,da),save(b.id,db)]);assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);
 const pending=await send('/api/registration-requests',{name:'New request',username:'identity-request',phone:'0500000000',password:'request-password',companyCode:a.companyCode,companyId:b.id,type:'admin',status:'approved'},{'Content-Type':'application/json'});assert.equal(pending.status,200);const request:any=await pending.json();assert.equal(request.companyId,a.id);assert.equal(request.status,'pending');
 assert.equal((await send('/api/registration-requests',{name:'Duplicate',username:'IDENTITY-REQUEST',phone:'0500000000',password:'request-password',companyCode:b.companyCode},{'Content-Type':'application/json'})).status,409);
 const decision=await send('/api/registration-requests/'+request.id,{status:'approved'},tenantHeaders(a.id),'PUT');assert.equal(decision.status,200);assert.equal((await main(a.id)).employees.filter((e:any)=>e.username==='identity-request').length,1);assert.equal((await send('/api/registration-requests/'+request.id,{status:'approved'},tenantHeaders(a.id),'PUT')).status,409);
 // Preexisting duplicate data is never silently reassigned or selected by password/company hint.
 const original=await main(b.id);await pool.query('UPDATE shift_app.system_data SET value=$1 WHERE key=$2',[JSON.stringify({...original,employees:[...original.employees,{...employee,id:'legacy-duplicate'}]}),'mainData_'+b.id]);assert.equal((await send('/api/auth/employee-login',{username:employee.username,password:employee.password,companyId:a.id},{'Content-Type':'application/json'})).status,401);await pool.query('UPDATE shift_app.system_data SET value=$1 WHERE key=$2',[JSON.stringify(original),'mainData_'+b.id]);
 const codeBefore=a.companyCode;assert.equal((await send('/api/companies',{id:a.id,adminPassword:'',companyCode:'999'})).status,403);const after:any=await (await fetch(origin+'/api/companies',{headers})).json();assert.equal(after.find((c:any)=>c.id===a.id).companyCode,codeBefore);
 assert.equal((await send('/api/companies',{id:b.id,subscriptionStatus:'suspended'})).status,200);assert.equal((await send('/api/auth/employee-login',{username:'identity-user-b',password:'employee-password'},{'Content-Type':'application/json'})).status,403);
 console.log('PASS: automatic immutable company codes, normalized cross-company login, global usernames/email namespace, transactional duplicate prevention, scoped JWTs, ambiguous legacy rejection, admin email login and atomic employee registration approval.');
}finally{child.kill('SIGTERM');await pool.end();await new Promise(r=>child.exitCode!==null?r(null):child.once('exit',r));}
