import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtempSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import pg from 'pg';
import jwt from 'jsonwebtoken';
import { emailVerificationKey, emailVerificationQuotaKey, verificationCodeHash, newVerificationState } from '../src/server/emailVerification';
const directory = mkdtempSync(join(tmpdir(), 'attendance-verification-'));
const capture = join(directory, 'mail.jsonl');
const secret = 'ci-verification-only-secret', companyId = 'verification-ci', id = 'verify-employee-ci';
const pool = new pg.Pool({ host: process.env.SQL_HOST, port: Number(process.env.SQL_PORT || 5432), user: process.env.SQL_USER, password: process.env.SQL_PASSWORD, database: process.env.SQL_DB_NAME });
const child = spawn(process.execPath, ['--import', './tests/mockResend.mjs', 'dist/server.cjs'], { env: { ...process.env, NODE_ENV: 'production', JWT_SECRET: secret, RESEND_API_KEY: 'mock-resend-key', RESEND_FROM: 'Attendance <attendance@example.com>', ATTENDANCE_TEST_EMAIL_CAPTURE: capture }, stdio: 'inherit' });
const origin = 'http://127.0.0.1:3011', key = emailVerificationKey(companyId, id), quotaKey = emailVerificationQuotaKey(companyId);
const headers = (role: string, empId = id) => ({ Authorization: 'Bearer ' + jwt.sign({ role, id: empId, name: 'Verification employee', companyId }, secret, { expiresIn: '1h' }), 'Content-Type': 'application/json' });
const employeeHeaders = headers('employee'), adminHeaders = headers('admin');
const verificationUrl = origin + '/api/employee-profile/email-verification';
const read = () => fetch(verificationUrl + '?companyId=' + companyId, { headers: employeeHeaders });
const send = (requestHeaders = employeeHeaders, body: any = {}) => fetch(verificationUrl + '/send?companyId=' + companyId, { method: 'POST', headers: requestHeaders, body: JSON.stringify(body) });
const confirm = (code: any, requestHeaders = employeeHeaders) => fetch(verificationUrl + '/confirm?companyId=' + companyId, { method: 'POST', headers: requestHeaders, body: JSON.stringify({ code, empId: 'someone-else', email: 'ignored@example.com' }) });
const emailSave = (email: string) => fetch(origin + '/api/employee-profile/email?companyId=' + companyId, { method: 'PATCH', headers: employeeHeaders, body: JSON.stringify({ email }) });
const mainData = () => fetch(origin + '/api/main-data?companyId=' + companyId, { headers: adminHeaders }).then(r => r.json()) as Promise<any>;
const adminSave = (value: any) => fetch(origin + '/api/main-data?companyId=' + companyId, { method: 'POST', headers: adminHeaders, body: JSON.stringify({ ...value, _baseVersion: value._version }) });
const storedChallenge = () => pool.query('SELECT value FROM shift_app.system_data WHERE key=$1', [key]).then(r => r.rows[0]?.value);
const setChallenge = (value: any) => pool.query('INSERT INTO shift_app.system_data (key,value) VALUES ($1,$2) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value', [key, JSON.stringify(value)]);
const allowResend = async () => { const state = await storedChallenge(); await setChallenge({ ...state, requestedAt: Date.now() - 61000 }); };
const mails = () => existsSync(capture) ? readFileSync(capture, 'utf8').trim().split('\n').filter(Boolean).map(line => JSON.parse(line)) : [];
const latestCode = () => mails().at(-1).payload.text.match(/: (\d{6})\n/)[1];
try {
  let ready = false;
  for (let attempt = 0; attempt < 60; attempt++) {
    try { if ((await fetch(origin + '/api/companies')).ok) { ready = true; break; } } catch {}
    await new Promise(resolve => setTimeout(resolve, 500));
  }
  assert.ok(ready);
  await pool.query('INSERT INTO shift_app.system_data (key,value) VALUES ($1,$2) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value', ['mainData_' + companyId, JSON.stringify({ departments: [], employees: [{ id, name: 'Verification employee', email: 'verify@example.com', password: 'untouched-password', dept: 'original' }, { id: 'other-employee-ci', name: 'Other employee', email: 'other@example.com' }], schedule: {}, shiftTypes: [], settings: { companyName: 'Verification company' } })]);
  await pool.query('DELETE FROM shift_app.system_data WHERE key IN ($1,$2)', [key, quotaKey]);
  assert.equal((await fetch(verificationUrl + '?companyId=' + companyId)).status, 401);
  assert.equal((await send(adminHeaders)).status, 403);
  assert.equal((await confirm('123456', adminHeaders)).status, 403);
  assert.equal((await fetch(verificationUrl + '?companyId=another-company', { headers: employeeHeaders })).status, 403);
  const before = await mainData();
  const initial = await read();
  assert.equal(initial.headers.get('cache-control'), 'private, no-store');
  assert.equal((await initial.json() as any).available, true);
  const concurrent = await Promise.all([send(employeeHeaders, { empId: 'other-employee-ci', email: 'ignored@example.com' }), send()]);
  assert.deepEqual(concurrent.map(r => r.status).sort(), [200, 429]);
  assert.equal(mails().length, 1);
  assert.deepEqual(mails()[0].payload.to, ['verify@example.com']);
  assert.ok(mails()[0].idempotencyKey.startsWith('employee-email-verification-'));
  const firstCode = latestCode(), challenge = await storedChallenge();
  assert.equal(challenge.codeHash, verificationCodeHash(secret, companyId, id, 'verify@example.com', challenge.nonce, firstCode));
  assert.equal(challenge.code, undefined);
  assert.equal(challenge.payload, undefined);
  const pending = await (await read()).json() as any;
  assert.equal(pending.codePending, true);
  assert.equal(pending.codeHash, undefined);
  assert.equal(pending.nonce, undefined);
  assert.equal((await confirm('12345')).status, 400);
  assert.equal((await confirm(123456)).status, 400);
  const wrong = firstCode === '000000' ? '111111' : '000000';
  const invalid = await confirm(wrong);
  assert.equal(invalid.status, 400);
  assert.equal((await invalid.json() as any).attemptsRemaining, 4);
  assert.equal((await confirm(firstCode, headers('employee', 'other-employee-ci'))).status, 409);
  const duplicateConfirm = await Promise.all([confirm(firstCode), confirm(firstCode)]);
  assert.deepEqual(duplicateConfirm.map(r => r.status).sort(), [200, 409]);
  assert.equal((await storedChallenge()).codeHash, undefined);
  const verified = await mainData(), own = verified.employees.find((e: any) => e.id === id);
  assert.ok(own.emailVerifiedAt);
  assert.equal(own.emailVerifiedAddress, 'verify@example.com');
  assert.equal(own.password, 'untouched-password');
  assert.equal(own.dept, 'original');
  assert.equal(verified.employees.find((e: any) => e.id === 'other-employee-ci').emailVerifiedAt, undefined);
  assert.equal((await adminSave(before)).status, 409, 'verification invalidates stale administrator writes');
  const proofTime = own.emailVerifiedAt;
  verified.employees = verified.employees.map((e: any) => ({ ...e, emailVerifiedAt: 'forged', emailVerifiedAddress: 'forged@example.com' }));
  assert.equal((await adminSave(verified)).status, 200);
  const protectedData = await mainData();
  assert.equal(protectedData.employees.find((e: any) => e.id === id).emailVerifiedAt, proofTime);
  assert.equal(protectedData.employees.find((e: any) => e.id === 'other-employee-ci').emailVerifiedAt, undefined);
  assert.equal((await emailSave('VERIFY@example.com')).status, 200);
  assert.equal((await (await read()).json() as any).verified, true);
  assert.equal((await emailSave('new@example.com')).status, 200);
  assert.equal((await (await read()).json() as any).verified, false);
  assert.equal((await mainData()).employees.find((e: any) => e.id === id).emailVerifiedAt, undefined);
  assert.equal((await confirm(firstCode)).status, 409);
  assert.equal((await send()).status, 429, 'address changes cannot bypass the resend cooldown');
  await allowResend();
  assert.equal((await send()).status, 200);
  const secondCode = latestCode();
  assert.deepEqual(mails().at(-1).payload.to, ['new@example.com']);
  assert.equal((await emailSave('replacement@example.com')).status, 200);
  assert.equal((await confirm(secondCode)).status, 409);
  await allowResend();
  assert.equal((await send()).status, 200);
  const thirdCode = latestCode();
  if (thirdCode !== secondCode) assert.equal((await confirm(secondCode)).status, 400);
  // Reset attempt count only in the fixture, then exercise every locked incorrect attempt.
  await setChallenge({ ...await storedChallenge(), attempts: 0 });
  const wrongThird = thirdCode === '000000' ? '111111' : '000000';
  for (let attempt = 0; attempt < 5; attempt++) {
    const result = await confirm(wrongThird);
    assert.equal(result.status, 400);
    assert.equal((await result.json() as any).attemptsRemaining, 4 - attempt);
  }
  assert.equal((await confirm(thirdCode)).status, 429);
  assert.equal((await (await read()).json() as any).codePending, false);
  await setChallenge({ ...await storedChallenge(), attempts: 0, expiresAt: Date.now() - 1 });
  assert.equal((await confirm(thirdCode)).status, 409);
  await setChallenge({ ...await storedChallenge(), hourStartedAt: Date.now(), requestedAt: Date.now() - 61000, sendCount: 6 });
  const countBeforeLimits = mails().length;
  assert.equal((await send()).status, 429);
  await setChallenge({ ...await storedChallenge(), sendCount: 0 });
  await pool.query('UPDATE shift_app.system_data SET value=$1 WHERE key=$2', [JSON.stringify({ hourStartedAt: Date.now(), count: 100 }), quotaKey]);
  assert.equal((await send()).status, 429);
  assert.equal(mails().length, countBeforeLimits);
  await pool.query('UPDATE shift_app.system_data SET value=$1 WHERE key=$2', [JSON.stringify({ hourStartedAt: Date.now() - 3600001, count: 100 }), quotaKey]);
  assert.equal((await emailSave('fail@example.com')).status, 200);
  const uncertain = await send();
  assert.equal(uncertain.status, 503);
  assert.equal((await uncertain.json() as any).codePending, true);
  assert.equal((await storedChallenge()).delivery, 'failed');
  assert.equal((await confirm(latestCode())).status, 200, 'possession of a valid code resolves ambiguous provider failures');
  const events = await pool.query("SELECT details FROM shift_app.audit_log WHERE company_id=$1 AND entity_id=$2 AND action='employee.email.verify'", [companyId, id]);
  assert.equal(events.rows.length, 2);
  assert.ok(events.rows.every(row => !JSON.stringify(row.details).includes('codeHash') && row.details.code === undefined));
  const finalData = await mainData();
  finalData.employees = finalData.employees.map((e: any) => e.id === id ? { ...e, email: 'admin-change@example.com' } : e);
  assert.equal((await adminSave(finalData)).status, 200);
  assert.equal((await (await read()).json() as any).verified, false, 'administrator email changes also revoke the proof');
  const suspended = await mainData();
  suspended.employees = suspended.employees.map((e: any) => e.id === id ? { ...e, status: 'suspended', statusReason: 'CI inactive' } : e);
  assert.equal((await adminSave(suspended)).status, 200);
  assert.equal((await read()).status, 403);
  assert.equal((await send()).status, 403);
  assert.equal((await confirm('123456')).status, 403);
  console.log('PASS: email verification scopes identity, hashes OTPs, serializes send/confirm, protects proof metadata, revokes changed addresses, preserves other fields, and enforces expiry/attempt/hourly limits without real mail.');
} finally {
  child.kill('SIGTERM');
  await pool.end();
  await new Promise(resolve => { if (child.exitCode !== null) resolve(null); else child.once('exit', resolve); });
  rmSync(directory, { recursive: true, force: true });
}
