import { employeePhotoKey } from '../src/server/employeeSelfService';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import pg from 'pg';
import jwt from 'jsonwebtoken';
const origin='http://127.0.0.1:3011',secret='self-service-ci-only-secret',companyId='self-service-ci',id='self-employee';
const pool=new pg.Pool({host:process.env.SQL_HOST,port:Number(process.env.SQL_PORT || 5432),user:process.env.SQL_USER,password:process.env.SQL_PASSWORD,database:process.env.SQL_DB_NAME});
const child=spawn(process.execPath,['dist/server.cjs'],{env:{...process.env,NODE_ENV:'production',JWT_SECRET:secret,BACKUP_ENABLED:'false'},stdio:'inherit'});
const headers={Authorization:'Bearer '+jwt.sign({role:'employee',companyId,id},secret,{expiresIn:'1h'}),'Content-Type':'application/json'};
const request=(endpoint:string,method='GET',body?:any,auth:Record<string,string>=headers)=>fetch(origin+endpoint,{method,headers:auth,...(body===undefined?{}:{body:JSON.stringify(body)})});
const profileUrl='/api/employee-profile?companyId='+companyId;
try{
 let ready=false;for(let i=0;i<60;i++){try{if((await fetch(origin+'/api/health/live')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,500));}assert.ok(ready);
 await pool.query('INSERT INTO shift_app.companies(id,name,admin_username,admin_password) VALUES ($1,$2,$3,$4)',[companyId,'Self service company','self-master','hash']);
 const data={departments:[{id:'d',name:'Department'}],employees:[{id,name:'Official name',username:'self-service-user',dept:'d',phone:'old-phone',email:'self-original@example.com',emailVerifiedAt:'2026-01-01T00:00:00Z',emailVerifiedAddress:'self-original@example.com',password:'private-password',webauthnCredentials:[{id:'secret'}]},{id:'other-self-employee',name:'Other employee',username:'self-other-user',email:'self-other@example.com',password:'foreign-password',dept:'d'}],shiftTypes:[{id:'M',start:'08:00',end:'16:00'}],schedule:{'2024-10-01':{[id]:{shiftType:'M'}},'2024-10-02':{[id]:{shiftType:'M'}},'2024-10-03':{[id]:{shiftType:'OFF'}},'2024-10-04':{[id]:{shiftType:'M'}},'2024-10-05':{[id]:{shiftType:'M'}}},settings:{companyName:'Self service company'}};
 await pool.query('INSERT INTO shift_app.system_data(key,value) VALUES ($1,$2)',['mainData_'+companyId,JSON.stringify(data)]);
 assert.equal((await request(profileUrl,'GET',undefined,{})).status,401);
 assert.equal((await request('/api/employee-profile?companyId=default')).status,403);
 const root={'Content-Type':'application/json',Authorization:'Bearer '+jwt.sign({role:'superadmin',companyId:'default'},secret)};assert.equal((await request(profileUrl,'GET',undefined,root)).status,403);
 const own:any=await (await request(profileUrl+'&empId=other-self-employee')).json();assert.equal(own.id,id);assert.equal(own.password,undefined);assert.equal(own.webauthnCredentials,undefined);
 for(const field of ['id','empId','name','username','dept','status','password','emailVerifiedAt'])assert.equal((await request(profileUrl,'PATCH',{[field]:'forged'})).status,400);
 assert.equal((await request(profileUrl,'PATCH',{email:'SELF-OTHER@EXAMPLE.COM'})).status,409);
 const image='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aH0kAAAAASUVORK5CYII=';
 const edit={displayName:'My display name',phone:'0500000000',email:'SELF-UPDATED@EXAMPLE.COM',photoDataUrl:image};
 assert.equal((await request(profileUrl,'PATCH',edit)).status,200);
 const value=(await pool.query('SELECT value FROM shift_app.system_data WHERE key=$1',['mainData_'+companyId])).rows[0].value;
 assert.deepEqual(value.employees[1],data.employees[1]);assert.deepEqual(value.schedule,data.schedule);assert.equal(value.employees[0].name,'Official name');assert.equal(value.employees[0].password,'private-password');assert.equal(value.employees[0].emailVerifiedAt,undefined);assert.equal(value.employees[0].email,'self-updated@example.com');assert.equal(value.employees[0].photoDataUrl,undefined);assert.equal((await pool.query('SELECT value FROM shift_app.system_data WHERE key=$1',[employeePhotoKey(companyId,id)])).rows[0].value.dataUrl,image);
 const audited=await pool.query("SELECT details FROM shift_app.audit_log WHERE company_id=$1 AND action='employee.self-profile'",[companyId]);assert.equal(audited.rows.length,1);assert.ok(!JSON.stringify(audited.rows).includes(image));
 assert.equal((await request(profileUrl,'PATCH',edit)).status,200);assert.equal((await pool.query("SELECT count(*)::int AS count FROM shift_app.audit_log WHERE company_id=$1 AND action='employee.self-profile'",[companyId])).rows[0].count,1,'unchanged profile saves create no extra audit writes');
 assert.equal((await request(profileUrl,'PATCH',{photoDataUrl:'data:image/svg+xml;base64,PHN2Zz4='})).status,400);
 await pool.query("INSERT INTO shift_app.attendance(company_id,emp_id,emp_name,date,check_in,check_out,check_in_location,check_out_location,check_in_lat) VALUES ($1,$2,'Self','2024-10-01','08:10','16:00','المقر','فرع الدمام',24),($1,'other-self-employee','Other','2024-10-01','09:00','17:00','private-foreign-site','private-foreign-site',25),('another-self-company',$2,'Foreign company','2024-10-01','09:00','17:00','private-company-site','private-company-site',26)",[companyId,id]);
 await pool.query("INSERT INTO shift_app.requests(company_id,emp_id,emp_name,date,type,status) VALUES ($1,$2,'Self','2024-10-02','leave','approved')",[companyId,id]);
 const historyUrl='/api/employee-attendance?companyId='+companyId+'&month=2024-10';const reportResponse=await request(historyUrl+'&empId=other-self-employee');assert.equal(reportResponse.status,200);const report:any=await reportResponse.json();assert.equal(report.absentDays,2);assert.equal(report.totalMinutes,470);assert.equal(report.lateDays,1);
 const day=report.items.find((d:any)=>d.date==='2024-10-01');assert.equal(day.first.location,'المقر');assert.equal(day.last.location,'فرع الدمام');assert.ok(!JSON.stringify(report).includes('checkInLat'));assert.ok(!JSON.stringify(report).includes('private-foreign-site'));assert.ok(!JSON.stringify(report).includes('private-company-site'));assert.equal(day.records,undefined);
 assert.equal((await request(historyUrl.replace('2024-10','2024-99'))).status,400);assert.equal((await request(historyUrl.replace(companyId,'default'))).status,403);assert.equal((await request(historyUrl,'GET',undefined,root)).status,403);
 const after=(await pool.query('SELECT value FROM shift_app.system_data WHERE key=$1',['mainData_'+companyId])).rows[0].value;assert.deepEqual(after,value,'reading report never rewrites schedule or profile');
 const main:any=await (await request('/api/main-data?companyId='+companyId)).json();assert.equal(main.employees.find((e:any)=>e.id===id).photoDataUrl,image);assert.equal(main.employees.find((e:any)=>e.id==='other-self-employee').email,undefined);
 assert.equal((await request(profileUrl,'PATCH',{photoDataUrl:''})).status,200);assert.equal((await pool.query('SELECT count(*)::int AS count FROM shift_app.system_data WHERE key=$1',[employeePhotoKey(companyId,id)])).rows[0].count,0);
 console.log('PASS: self-only profile and report, protected HR fields, atomic/global email checks and verification invalidation, bounded raster images and deletion, no-op writes, isolated first/last punches and locations, absence excludes leave/rest, read-only reports.');
}finally{child.kill('SIGTERM');await pool.end();await new Promise(r=>child.exitCode!==null?r(null):child.once('exit',r));}
