import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import pg from 'pg';
import bcrypt from 'bcryptjs';
import crypto from 'node:crypto';
import jwt from 'jsonwebtoken';
import { mainDataVersion } from '../src/lib/mainDataVersion';

const pool = new pg.Pool({ host: process.env.SQL_HOST, port: Number(process.env.SQL_PORT || 5432), user: process.env.SQL_USER, password: process.env.SQL_PASSWORD, database: process.env.SQL_DB_NAME });
const child = spawn(process.execPath, ['dist/server.cjs'], { env: { ...process.env, NODE_ENV: 'production', JWT_SECRET: 'ci-integration-only-secret' }, stdio: 'inherit' });
const origin = 'http://127.0.0.1:3011';
try {
  let ready = false;
  for (let attempt = 0; attempt < 60; attempt++) {
    try { const response = await fetch(origin + '/api/companies'); if (response.ok) { ready = true; break; } } catch {}
    await new Promise(resolve => setTimeout(resolve, 500));
  }
  assert.ok(ready, 'server started');
  const value = { departments: [], employees: [{ id:'employee-ci', name:'Branch employee', username:'branch-user', password:'employee-password', restrictAttendanceLocations:true, allowedAttendanceLocationIds:['east'] }], shiftTypes: [], schedule: {}, settings: {
    companyName: 'CI', password: bcrypt.hashSync('ci-password', 10),
    officeLocation: { lat:24, lng:46, radius:150, preventOutCheckout:true },
    attendanceLocations:[{id:'east',name:'الشرقية',lat:26,lng:50,radius:100}]
  } };
  await pool.query('INSERT INTO shift_app.system_data (key, value) VALUES ($1, $2) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value', ['mainData', JSON.stringify(value)]);
  const login = await fetch(origin + '/api/auth/admin-login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'admin', password: 'ci-password', companyId: 'default' }) });
  assert.equal(login.status, 200);
  const { token } = await login.json() as any;
  const headers = { Authorization: 'Bearer ' + token, 'Content-Type': 'application/json' };
  const response = await fetch(origin + '/api/main-data?companyId=default', { headers });
  const initial = await response.json() as any;
  assert.ok(initial._version);
  const save = (name: string, version: string | undefined) => fetch(origin + '/api/main-data?companyId=default', { method: 'POST', headers, body: JSON.stringify({ ...initial, settings: { ...initial.settings, companyName: name }, _baseVersion: version }) });
  const simultaneous = await Promise.all([save('Manager A', initial._version), save('Manager B', initial._version)]);
  assert.deepEqual(simultaneous.map(r => r.status).sort(), [200, 409]);
  assert.equal((await save('Stale', initial._version)).status, 409);
  assert.equal((await save('Old client', undefined)).status, 409);
  const latestResponse = await fetch(origin + '/api/main-data?companyId=default', { headers });
  const latest = await latestResponse.json() as any;
  assert.ok(['Manager A', 'Manager B'].includes(latest.settings.companyName));
  assert.equal((await save('Fresh', latest._version)).status, 200);
  const stored = await pool.query('SELECT value FROM shift_app.system_data WHERE key=$1', ['mainData']);
  assert.equal(stored.rows[0].value._baseVersion, undefined);
  assert.equal(stored.rows[0].value._version, undefined);
  const employeeLogin = await fetch(origin + '/api/auth/employee-login', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({companyId:'default', username:'branch-user',password:'employee-password'}) });
  assert.equal(employeeLogin.status,200);
  const employee = await employeeLogin.json() as any;
  const employeeHeaders = { Authorization:'Bearer ' + employee.token, 'Content-Type':'application/json' };
  const beforeEmailProfile = await (await fetch(origin + '/api/main-data?companyId=default', { headers })).json() as any;
  const emailUrl = origin + '/api/employee-profile/email?companyId=default';
  const emailSave = (body: any, requestHeaders = employeeHeaders, url = emailUrl) => fetch(url, { method: 'PATCH', headers: requestHeaders, body: JSON.stringify(body) });
  assert.equal((await emailSave({ email: 'employee@example.com' }, headers)).status, 403);
  assert.equal((await emailSave({ email: 'bad' })).status, 400);
  assert.equal((await emailSave({ email: 'employee@example.com' }, employeeHeaders, emailUrl.replace('default', 'another-company'))).status, 403);
  assert.equal((await emailSave({ email: ' employee@example.com ', empId: 'another-employee', password: 'bad-password', schedule: {} })).status, 200);
  const savedProfile = (await pool.query('SELECT value FROM shift_app.system_data WHERE key=$1', ['mainData'])).rows[0].value;
  assert.equal(savedProfile.employees[0].email, 'employee@example.com');
  assert.equal(savedProfile.employees[0].password, 'employee-password');
  assert.equal(savedProfile.employees[0].allowedAttendanceLocationIds[0], 'east');
  assert.equal(savedProfile.settings.companyName, 'Fresh');
  const emailRead = await (await fetch(origin + '/api/main-data?companyId=default', { headers: employeeHeaders })).json() as any;
  assert.equal(emailRead.employees[0].email, 'employee@example.com');
  // Profile writes change the version, so a stale administrator cannot overwrite them.
  assert.equal((await save('Stale after profile update', beforeEmailProfile._version)).status, 409);
  console.log('PASS: employee email updates use token identity, validate tenant/email, preserve password and settings, and invalidate stale admin saves.');
  const welcomeUrl = origin + '/api/employees/employee-ci/welcome-email?companyId=default';
  assert.equal((await fetch(welcomeUrl, { method: 'POST' })).status, 401);
  assert.equal((await fetch(welcomeUrl, { method: 'POST', headers: employeeHeaders })).status, 403);
  assert.equal((await fetch(welcomeUrl.replace('default', 'another-company'), { method: 'POST', headers: employeeHeaders })).status, 403);
  assert.equal((await fetch(origin + '/api/employees/missing/welcome-email?companyId=default', { method: 'POST', headers })).status, 404);
  assert.equal((await fetch(welcomeUrl, { method: 'POST', headers, body: JSON.stringify({ email: 'ignored@example.com' }) })).status, 503);
  const welcomeKey = 'welcomeEmail_' + crypto.createHash('sha256').update(JSON.stringify(['default', 'employee-ci'])).digest('hex');
  await pool.query('INSERT INTO shift_app.system_data (key,value) VALUES ($1,$2)', [welcomeKey, JSON.stringify({ status: 'sent', providerId: 'mock-accepted' })]);
  const acceptedAgain = await fetch(welcomeUrl, { method: 'POST', headers });
  assert.equal(acceptedAgain.status, 200);
  assert.equal((await acceptedAgain.json() as any).status, 'sent');
  await pool.query('UPDATE shift_app.system_data SET value=$1 WHERE key=$2', [JSON.stringify({ status: 'failed', startedAt: Date.now() - 24 * 3600000 }), welcomeKey]);
  assert.equal((await fetch(welcomeUrl, { method: 'POST', headers })).status, 409);
  await pool.query('DELETE FROM shift_app.system_data WHERE key=$1', [welcomeKey]);
  console.log('PASS: welcome mail requires admin authentication and stored recipient, suppresses accepted duplicates and expired retries.');
  const punch = (body: any) => fetch(origin + '/api/attendance', { method:'POST',headers:employeeHeaders,body:JSON.stringify({companyId:'default',...body}) });
  assert.equal((await punch({empId:'employee-ci',checkIn:'08:00',checkInLat:24,checkInLng:46})).status,403);
  assert.equal((await punch({empId:'employee-ci',checkIn:'08:00'})).status,403);
  assert.equal((await punch({ checkIn: 'auto', checkInLat: 26, checkInLng: 50, automatic: true, gpsAccuracy: 200, gpsTimestamp: Date.now() })).status, 400);
  assert.equal((await punch({ checkIn: 'auto', checkInLat: 26, checkInLng: 50, automatic: true, gpsAccuracy: 10, gpsTimestamp: Date.now() - 60000 })).status, 400);
  const repeats = await Promise.all([punch({empId:'employee-ci',checkIn:'08:00',checkInLat:26,checkInLng:50,automatic:true,gpsAccuracy:10,gpsTimestamp:Date.now()}),punch({empId:'employee-ci',checkIn:'08:00',checkInLat:26,checkInLng:50,automatic:true,gpsAccuracy:10,gpsTimestamp:Date.now()})]);
  assert.deepEqual(repeats.map(r=>r.status),[200,200]);
  const attendance = await repeats[0].json() as any;
  assert.equal(attendance.checkInLocation,'الشرقية');
  assert.equal(attendance.source, 'GPS تلقائي');
  assert.equal((await punch({ id: attendance.id, checkOut: 'auto', automatic: true })).status, 400);
  const savedRows = await pool.query('SELECT count(*)::int AS count FROM shift_app.attendance WHERE emp_id=$1',['employee-ci']);
  assert.equal(savedRows.rows[0].count,1);
  assert.equal((await punch({id:attendance.id,checkOut:'17:00',checkOutLat:24,checkOutLng:46})).status,403);
  assert.equal((await punch({id:attendance.id,checkOut:'17:00',checkOutLat:26,checkOutLng:50})).status,200);
  const events = await pool.query("SELECT count(*)::int AS count FROM shift_app.audit_log WHERE actor_id=$1 AND action LIKE 'punch.%'",['employee-ci']);
  assert.equal(events.rows[0].count,2);
  const month = '2025-01';
  const adminRecord = (body: any) => fetch(origin + '/api/attendance', { method: 'POST', headers, body: JSON.stringify({ companyId: 'default', ...body }) });
  const monthly = (body: any) => fetch(origin + '/api/attendance-months', { method: 'POST', headers, body: JSON.stringify({ companyId: 'default', month, ...body }) });
  assert.equal((await fetch(origin + '/api/attendance-months?companyId=default', { method: 'POST', headers, body: JSON.stringify({ companyId: 'other-company', month, action: 'approve' }) })).status, 400);
  const historical = { empId: 'monthly-ci', empName: 'Monthly employee', date: month + '-10', checkIn: '08:00', checkOut: '17:00', source: 'تسجيل إداري' };
  const created = await adminRecord(historical);
  assert.equal(created.status, 200);
  const record = await created.json() as any;
  assert.equal((await monthly({ action: 'approve', month: new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Riyadh' }).slice(0, 7) })).status, 400);
  assert.equal((await fetch(origin + '/api/attendance-months?companyId=default&month=' + month, { headers: employeeHeaders })).status, 403);
  const approved = await monthly({ action: 'approve' });
  assert.equal(approved.status, 200);
  const frozen = await approved.json() as any;
  assert.equal(frozen.status, 'approved');
  assert.equal(frozen.snapshot.totalMinutes, 540);
  assert.equal(frozen.snapshot.days[0].empName, 'Monthly employee');
  assert.equal((await adminRecord({ id: record.id, note: 'blocked correction' })).status, 409);
  assert.equal((await adminRecord({ id: record.id, date: '2025-02-10' })).status, 409);
  assert.equal((await adminRecord(historical)).status, 409);
  assert.equal((await fetch(origin + '/api/attendance/' + record.id, { method: 'DELETE', headers })).status, 409);
  const outside = await adminRecord({ ...historical, date: '2025-02-10' });
  assert.equal(outside.status, 200);
  const outsideRecord = await outside.json() as any;
  assert.equal((await adminRecord({ id: outsideRecord.id, date: month + '-11' })).status, 409);
  assert.equal((await monthly({ action: 'reopen', reason: '' })).status, 400);
  assert.equal((await monthly({ action: 'reopen', reason: 'تصحيح إداري موثق' })).status, 200);
  assert.equal((await adminRecord({ id: record.id, note: 'allowed correction' })).status, 200);
  assert.equal((await monthly({ action: 'approve' })).status, 200);
  const monthAudit = await pool.query("SELECT action, details FROM shift_app.audit_log WHERE entity_id=$1 AND action LIKE 'attendance.month.%' ORDER BY id", [month]);
  assert.deepEqual(monthAudit.rows.map(row => row.action), ['attendance.month.approve', 'attendance.month.reopen', 'attendance.month.approve']);
  assert.equal(monthAudit.rows[1].details.reason, 'تصحيح إداري موثق');
  const raceMonth = '2024-12';
  assert.equal((await adminRecord({ ...historical, date: raceMonth + '-10' })).status, 200);
  const [raceWrite, raceApprove] = await Promise.all([
    adminRecord({ ...historical, date: raceMonth + '-11' }),
    monthly({ month: raceMonth, action: 'approve' }),
  ]);
  assert.equal(raceApprove.status, 200);
  const raceSnapshot = await raceApprove.json() as any;
  assert.ok([200, 409].includes(raceWrite.status));
  assert.equal(raceSnapshot.snapshot.days.length, raceWrite.status === 200 ? 2 : 1);
  const raceRows = await pool.query("SELECT count(*)::int AS count FROM shift_app.attendance WHERE date LIKE $1", [raceMonth + '-%']);
  assert.equal(raceRows.rows[0].count, raceSnapshot.snapshot.days.length);
  assert.equal((await monthly({ month: raceMonth, action: 'reopen', reason: 'stale browser attempt', expectedStatus: 'approved', expectedRevision: 0 })).status, 409);
  const reportRecords = Array.from({ length: 53 }, (_, i) => ({ emp_id: 'report-' + i, emp_name: 'Report ' + i, dept: 'report-dept', date: '2024-11-10', check_in: '08:00', check_out: '17:00', company_id: 'default' }));
  reportRecords.push({ ...reportRecords[0] });
  reportRecords.push({ ...reportRecords[0], company_id: 'foreign-company' });
  await pool.query(`INSERT INTO shift_app.attendance (emp_id,emp_name,dept,date,check_in,check_out,company_id)
    SELECT emp_id,emp_name,dept,date,check_in,check_out,company_id FROM jsonb_to_recordset($1::jsonb) AS r(emp_id text,emp_name text,dept text,date text,check_in text,check_out text,company_id text)`, [JSON.stringify(reportRecords)]);
  const reportQuery = '/api/attendance-report?companyId=default&from=2024-11-10&to=2024-11-10&dept=report-dept';
  const firstPage = await fetch(origin + reportQuery, { headers }); assert.equal(firstPage.status, 200);
  const firstReport = await firstPage.json() as any;
  assert.equal(firstReport.items.length, 50); assert.equal(firstReport.total, 53); assert.equal(firstReport.totalMinutes, 53 * 540);
  const secondReport = await (await fetch(origin + reportQuery + '&page=2', { headers })).json() as any;
  assert.equal(secondReport.items.length, 3);
  const fullReport = await (await fetch(origin + reportQuery + '&mode=all', { headers })).json() as any;
  assert.equal(fullReport.items.length, 53);
  const employeeReport = await (await fetch(origin + reportQuery + '&empId=report-0', { headers })).json() as any;
  assert.equal(employeeReport.total, 1); assert.equal(employeeReport.items[0].ids.length, 2);
  assert.equal((await fetch(origin + reportQuery, { headers: employeeHeaders })).status, 403);
  assert.equal((await fetch(origin + '/api/attendance-report?companyId=default&from=2026-02-30', { headers })).status, 400);
  const historicalLookup = await (await fetch(origin + '/api/attendance?companyId=default&from=2024-11-10&to=2024-11-10&empId=report-0', { headers })).json() as any;
  assert.equal(historicalLookup.length, 2);
  const employeeScope = await (await fetch(origin + '/api/attendance?companyId=default&empId=report-0', { headers: employeeHeaders })).json() as any;
  assert.ok(employeeScope.every((row: any) => row.empId === 'employee-ci'));
  const analysisData = { ...stored.rows[0].value,
    employees: [...stored.rows[0].value.employees, { id: 'analysis-ci', name: 'Analysis employee', dept: 'analysis-dept' }],
    shiftTypes: [{ id: 'S', start: '08:00', end: '17:00' }, { id: 'N', start: '22:00', end: '06:00' }],
    schedule: { '2024-10-10': { 'analysis-ci': { shiftType: 'S' } }, '2024-10-11': { 'analysis-ci': { shiftType: 'A' } }, '2024-10-12': { 'analysis-ci': { shiftType: 'N' } }, '2024-10-13': { 'analysis-ci': { shiftType: 'S' } } },
    settings: { ...stored.rows[0].value.settings, attendanceAnalysis: { graceMinutes: 5 } },
  };
  (analysisData as any)._schedulePublication = { schedule: analysisData.schedule, shiftTypes: analysisData.shiftTypes, publishedAt: null };
  await pool.query('UPDATE shift_app.system_data SET value=$1 WHERE key=$2', [JSON.stringify(analysisData), 'mainData']);
  await pool.query("INSERT INTO shift_app.requests (emp_id,emp_name,date,type,status,company_id) VALUES ('analysis-ci','Analysis employee','2024-10-10','leave','approved','default')");
  assert.equal((await adminRecord({ empId: 'analysis-ci', empName: 'Analysis employee', dept: 'analysis-dept', date: '2024-10-13', checkIn: '08:15', checkOut: '17:30' })).status, 200);
  const analysisQuery = '/api/attendance-report?companyId=default&from=2024-10-10&to=2024-10-13&empId=analysis-ci&analysis=1&mode=all';
  const analyzed = await (await fetch(origin + analysisQuery, { headers })).json() as any;
  assert.equal(analyzed.total, 4); assert.equal(analyzed.absentDays, 1); assert.equal(analyzed.lateMinutes, 10); assert.equal(analyzed.overtimeMinutes, 30); assert.equal(analyzed.reviewCount, 0);
  assert.equal(analyzed.items.find((day: any) => day.date === '2024-10-10').analysis.status, 'إجازة معتمدة');
  const absences = await (await fetch(origin + analysisQuery + '&status=absent', { headers })).json() as any;
  assert.equal(absences.total, 1); assert.equal(absences.items[0].date, '2024-10-12'); assert.deepEqual(absences.items[0].ids, []);
  // An employee holding an older HTTP entity must receive new and cleared schedules.
  const beforeEmployee = await fetch(origin + '/api/main-data?companyId=default', {headers:employeeHeaders});
  const oldEntity = beforeEmployee.headers.get('etag');
  assert.equal(beforeEmployee.headers.get('cache-control'), 'private, no-store');
  assert.ok(beforeEmployee.headers.get('vary')?.includes('Authorization'));
  const beforeEdit = await (await fetch(origin + '/api/main-data?companyId=default', {headers})).json() as any;
  const updatedSchedule = {...beforeEdit.schedule, '2026-10-03':{'employee-ci':{shiftType:'S',note:'Updated by manager'}}};
  const editedResponse = await fetch(origin + '/api/main-data?companyId=default', {method:'POST',headers,body:JSON.stringify({...beforeEdit,schedule:updatedSchedule,_schedulePublication:{schedule:updatedSchedule,shiftTypes:beforeEdit.shiftTypes},_baseVersion:beforeEdit._version})});
  assert.equal(editedResponse.status,200);
  const edited = await editedResponse.json() as any;
  const afterEmployee = await fetch(origin + '/api/main-data?companyId=default', {headers:{...employeeHeaders,...(oldEntity ? {'If-None-Match':oldEntity} : {})}});
  assert.equal(afterEmployee.status,200);
  const employeeData = await afterEmployee.json() as any;
  assert.equal(employeeData.schedule['2026-10-03'], undefined, 'employee never sees draft assignments');
  assert.equal(employeeData._schedulePublication, undefined, 'employee does not receive private draft/publication payload');
  const publish = (signature: string, requestHeaders = headers) => fetch(origin + '/api/schedule-publication?companyId=default', { method: 'POST', headers: requestHeaders, body: JSON.stringify({ expectedSignature: signature }) });
  const signature = mainDataVersion({ schedule: updatedSchedule, shiftTypes: edited.shiftTypes });
  assert.equal((await publish(signature, employeeHeaders)).status, 403);
  assert.equal((await publish('0'.repeat(64))).status, 409);
  assert.equal((await publish(signature)).status, 200);
  assert.equal((await publish(signature)).status, 200, 'duplicate publication is a no-op');
  const publishedEmployee = await (await fetch(origin + '/api/main-data?companyId=default', { headers: employeeHeaders })).json() as any;
  assert.equal(publishedEmployee.schedule['2026-10-03']['employee-ci'].note, 'Updated by manager');
  assert.notEqual(publishedEmployee.scheduleNotice.revision, employeeData.scheduleNotice.revision);
  const latestPublished = await (await fetch(origin + '/api/main-data?companyId=default', { headers })).json() as any;
  const clearedResponse = await fetch(origin + '/api/main-data?companyId=default', {method:'POST',headers,body:JSON.stringify({...latestPublished,schedule:{},_baseVersion:latestPublished._version})});
  assert.equal(clearedResponse.status,200);
  const clearedEmployee = await (await fetch(origin + '/api/main-data?companyId=default', {headers:employeeHeaders})).json() as any;
  assert.equal(clearedEmployee.schedule['2026-10-03']['employee-ci'].note, 'Updated by manager', 'clearing the draft does not erase published schedule');
  assert.equal((await publish(mainDataVersion({ schedule: {}, shiftTypes: latestPublished.shiftTypes }))).status, 200);
  const finalClearedEmployee = await (await fetch(origin + '/api/main-data?companyId=default', { headers: employeeHeaders })).json() as any;
  assert.deepEqual(finalClearedEmployee.schedule, {});
  assert.notEqual(finalClearedEmployee.scheduleNotice.revision, publishedEmployee.scheduleNotice.revision);
  const publishAudit = await pool.query("SELECT count(*)::int AS count FROM shift_app.audit_log WHERE action='schedule.publish'");
  assert.equal(publishAudit.rows[0].count, 2);
  const changeStatus = async (status: string) => {
    const data = await (await fetch(origin + '/api/main-data?companyId=default', { headers })).json() as any;
    return fetch(origin + '/api/main-data?companyId=default', { method: 'POST', headers, body: JSON.stringify({ ...data, employees: data.employees.map((e: any) => e.id === 'employee-ci' ? { ...e, status, statusReason: 'CI lifecycle test' } : e), _baseVersion: data._version }) });
  };
  assert.equal((await changeStatus('invalid')).status, 400);
  for (const status of ['suspended', 'archived']) {
    assert.equal((await changeStatus(status)).status, 200);
    assert.equal((await fetch(origin + '/api/auth/employee-login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ companyId: 'default', username: 'branch-user', password: 'employee-password' }) })).status, 403);
    assert.equal((await fetch(origin + '/api/main-data?companyId=default', { headers: employeeHeaders })).status, 403);
    assert.equal((await punch({ checkIn: '08:00', checkInLat: 26, checkInLng: 50 })).status, 403);
    assert.equal((await emailSave({ email: 'blocked@example.com' })).status, 403);
    assert.equal((await fetch(origin + '/api/auth/webauthn-challenge', { method: 'POST', headers, body: JSON.stringify({ companyId: 'default', empId: 'employee-ci' }) })).status, 403);
  }
  const afterArchive = await (await fetch(origin + '/api/main-data?companyId=default', { headers })).json() as any;
  assert.ok(afterArchive.employees.some((e: any) => e.id === 'employee-ci'));
  assert.equal((await fetch(origin + '/api/main-data?companyId=default', { method: 'POST', headers, body: JSON.stringify({ ...afterArchive, employees: afterArchive.employees.filter((e: any) => e.id !== 'employee-ci'), _baseVersion: afterArchive._version }) })).status, 400);
  assert.equal((await changeStatus('active')).status, 200);
  assert.equal((await fetch(origin + '/api/main-data?companyId=default', { headers: employeeHeaders })).status, 200);
  const staffLog = await (await fetch(origin + '/api/employee-audit?companyId=default&empId=employee-ci', { headers })).json() as any;
  assert.deepEqual(staffLog.filter((e: any) => e.action === 'employee.status').map((e: any) => e.details.changes.status.after), ['active', 'archived', 'suspended']);
  assert.ok(staffLog.every((e: any) => e.entityId === 'employee-ci' && e.companyId === 'default'));
  assert.ok(!JSON.stringify(staffLog).includes('employee-password'));
  assert.equal((await fetch(origin + '/api/employee-audit?companyId=default&empId=employee-ci', { headers: employeeHeaders })).status, 403);
  assert.equal((await pool.query('SELECT count(*)::int AS count FROM shift_app.attendance WHERE emp_id=$1', ['employee-ci'])).rows[0].count, 1);
  const correction = (body: any) => fetch(origin + '/api/requests', { method: 'POST', headers: employeeHeaders, body: JSON.stringify({ companyId: 'default', empId: 'employee-ci', date: '2025-03-10', type: 'attendance_adjustment', note: 'Forgot checkout', checkOutTime: '17:00', ...body }) });
  assert.equal((await correction({ note: '' })).status, 400);
  assert.equal((await correction({ checkOutTime: '25:00' })).status, 400);
  assert.equal((await correction({ empId: 'someone-else' })).status, 403);
  assert.equal((await adminRecord({ empId: 'employee-ci', empName: 'Branch employee', date: '2025-03-10', checkIn: '08:00', checkInTs: String(Date.parse('2025-03-10T08:00:00+03:00')), note: 'original note' })).status, 200);
  const submitted = await correction({});
  assert.equal(submitted.status, 200);
  const correctionRequest = await submitted.json() as any;
  assert.equal(correctionRequest.status, 'pending');
  assert.equal((await correction({})).status, 409);
  const decide = (id: number, status: string, requestHeaders = headers) => fetch(origin + '/api/requests/' + id, { method: 'PUT', headers: requestHeaders, body: JSON.stringify({ status, reviewReason: 'CI reviewed evidence' }) });
  assert.equal((await decide(correctionRequest.id, 'approved', employeeHeaders)).status, 403);
  const decisions = await Promise.all([decide(correctionRequest.id, 'approved'), decide(correctionRequest.id, 'approved')]);
  assert.deepEqual(decisions.map(r => r.status), [200, 200]);
  const corrected = (await pool.query("SELECT * FROM shift_app.attendance WHERE emp_id='employee-ci' AND date='2025-03-10'")).rows[0];
  assert.equal(corrected.check_in, '08:00');
  assert.equal(corrected.check_out, '17:00');
  assert.match(corrected.note, /original note/);
  assert.match(corrected.check_out_location, /دون إثبات موقع/);
  const correctionAudit = (await pool.query("SELECT details FROM shift_app.audit_log WHERE action='attendance.correction.approve' AND details->>'requestId'=$1", [String(correctionRequest.id)])).rows;
  assert.equal(correctionAudit.length, 1);
  assert.equal(correctionAudit[0].details.before.checkOut, null);
  assert.equal(correctionAudit[0].details.after.checkOut, '17:00');
  assert.equal((await decide(correctionRequest.id, 'rejected')).status, 409);
  const stale = await (await correction({ checkOutTime: '18:00' })).json() as any;
  await pool.query("UPDATE shift_app.attendance SET note='changed after request' WHERE id=$1", [corrected.id]);
  assert.equal((await decide(stale.id, 'approved')).status, 409);
  assert.equal((await pool.query('SELECT status FROM shift_app.requests WHERE id=$1', [stale.id])).rows[0].status, 'pending');
  assert.equal((await decide(stale.id, 'rejected')).status, 200);
  const closed = await (await correction({ date: month + '-12', checkInTime: '08:00', checkOutTime: '17:00' })).json() as any;
  assert.equal((await decide(closed.id, 'approved')).status, 409);
  assert.equal((await pool.query('SELECT status FROM shift_app.requests WHERE id=$1', [closed.id])).rows[0].status, 'pending');
  assert.equal((await decide(closed.id, 'rejected')).status, 200);
  const employmentSave = (data: any) => fetch(origin + '/api/main-data?companyId=default', { method: 'POST', headers, body: JSON.stringify({ ...data, _baseVersion: data._version }) });
  let employmentData = await (await fetch(origin + '/api/main-data?companyId=default', { headers })).json() as any;
  employmentData.employees.push({ id: 'dated-ci', name: 'Dated employee', dept: 'original', employmentHistory: { dept: [{ date: '2000-01-01', before: 'forged' }] } });
  const createdEmployment = await employmentSave(employmentData);
  assert.equal(createdEmployment.status, 200);
  employmentData = await createdEmployment.json();
  assert.equal(employmentData.employees.find((e: any) => e.id === 'dated-ci').employmentHistory, undefined);
  employmentData.employees = employmentData.employees.map((e: any) => e.id === 'dated-ci' ? { ...e, dept: 'transferred', _employmentEffectiveDate: '2024-10-02' } : e);
  const datedTransfer = await employmentSave(employmentData);
  assert.equal(datedTransfer.status, 200);
  employmentData = await datedTransfer.json();
  const datedEmployee = employmentData.employees.find((e: any) => e.id === 'dated-ci');
  assert.deepEqual(datedEmployee.employmentHistory.dept, [{ date: '2024-10-02', before: 'original', after: 'transferred' }]);
  assert.equal(datedEmployee._employmentEffectiveDate, undefined);
  const invalidEmployment = { ...employmentData, employees: employmentData.employees.map((e: any) => e.id === 'dated-ci' ? { ...e, dept: 'future', _employmentEffectiveDate: '2099-01-01' } : e) };
  assert.equal((await employmentSave(invalidEmployment)).status, 400);
  employmentData.employees = employmentData.employees.map((e: any) => e.id === 'dated-ci' ? { ...e, name: 'Renamed', employmentHistory: {} } : e);
  const preservedEmployment = await employmentSave(employmentData);
  assert.equal(preservedEmployment.status, 200);
  assert.deepEqual((await preservedEmployment.json() as any).employees.find((e: any) => e.id === 'dated-ci').employmentHistory, datedEmployee.employmentHistory);
  assert.equal((await emailSave({ email: 'profile@example.com' })).status, 200);
  const profileUrl = origin + '/api/employees/employee-ci/profile?companyId=default&month=2025-03';
  const profileRead = (section: string, extra = '', requestHeaders = headers) => fetch(profileUrl + '&section=' + section + extra, { headers: requestHeaders });
  assert.equal((await fetch(profileUrl)).status, 401);
  assert.equal((await profileRead('overview', '', employeeHeaders)).status, 403);
  const tenantAdminHeaders = { ...headers, Authorization: 'Bearer ' + jwt.sign({ role: 'admin', companyId: 'default', id: 'tenant-admin-ci', name: 'Tenant admin' }, 'ci-integration-only-secret', { expiresIn: '1h' }) };
  assert.equal((await fetch(profileUrl, { headers: tenantAdminHeaders })).status, 200);
  assert.equal((await fetch(profileUrl.replace('companyId=default', 'companyId=another-company'), { headers: tenantAdminHeaders })).status, 403);
  assert.equal((await fetch(profileUrl.replace('companyId=default', 'companyId=another-company'), { headers })).status, 404, 'superadmin may select another company, but employee membership is still required');
  assert.equal((await fetch(profileUrl.replace('employee-ci', 'unknown-ci'), { headers })).status, 404);
  assert.equal((await profileRead('private')).status, 400);
  assert.equal((await profileRead('requests', '&page=0')).status, 400);
  assert.equal((await fetch(profileUrl.replace('2025-03', '2025-13'), { headers })).status, 400);
  const overviewResponse = await profileRead('overview');
  assert.equal(overviewResponse.headers.get('cache-control'), 'private, no-store');
  const overviewProfile = await overviewResponse.json() as any;
  assert.equal(overviewProfile.employee.id, 'employee-ci');
  assert.equal(overviewProfile.employee.email, 'profile@example.com');
  assert.equal(overviewProfile.employee.password, undefined);
  assert.equal(overviewProfile.employee.webauthnCredentials, undefined);
  const attendanceProfile = await (await profileRead('attendance')).json() as any;
  assert.equal(attendanceProfile.items.length, 1);
  assert.equal(attendanceProfile.items[0].date, '2025-03-10');
  assert.equal(attendanceProfile.totalMinutes, 540);
  assert.ok(attendanceProfile.items[0].last.location.includes('دون إثبات موقع'));
  assert.equal(attendanceProfile.items[0].checkInLat, undefined);
  const historyProfile = await (await profileRead('history')).json() as any;
  assert.ok(historyProfile.items.length > 0);
  assert.ok(historyProfile.items.every((row: any) => row.entityId === 'employee-ci' && row.companyId === 'default'));
  assert.ok(!JSON.stringify(historyProfile).includes('employee-password'));
  await pool.query("INSERT INTO shift_app.requests (emp_id,emp_name,date,type,notes,status,company_id) SELECT 'employee-ci','Branch employee','2025-03-11','leave','Profile request ' || n,'pending','default' FROM generate_series(1,25) n");
  await pool.query("INSERT INTO shift_app.requests (emp_id,emp_name,date,type,notes,status,company_id) VALUES ('someone-else','Other','2025-03-11','leave','other-private-note','pending','default'), ('employee-ci','Other tenant','2025-03-11','leave','tenant-private-note','pending','another-company')");
  const firstRequestPage = await (await profileRead('requests')).json() as any;
  const secondRequestPage = await (await profileRead('requests', '&page=2')).json() as any;
  assert.equal(firstRequestPage.items.length, 20);
  assert.equal(firstRequestPage.pending, 25);
  assert.equal(firstRequestPage.total, 27);
  assert.equal(secondRequestPage.items.length, 7);
  assert.equal(secondRequestPage.pageCount, 2);
  const profileCorrection = secondRequestPage.items.find((r: any) => r.id === correctionRequest.id);
  assert.equal(profileCorrection.originalCheckIn, '08:00');
  assert.equal(profileCorrection.originalCheckOut, null);
  assert.equal(profileCorrection.period, 1);
  assert.equal(profileCorrection.details, undefined);
  assert.ok(secondRequestPage.items.every((r: any) => !firstRequestPage.items.some((other: any) => other.id === r.id)));
  assert.ok(!JSON.stringify([firstRequestPage, secondRequestPage]).includes('private-note'));
  assert.equal((await (await profileRead('requests', '&page=999')).json() as any).page, 2);
  let profileMainData = await (await fetch(origin + '/api/main-data?companyId=default', { headers })).json() as any;
  profileMainData.schedule = { '2025-03-10': { 'employee-ci': { shiftType: 'S', note: 'Profile published note' }, 'dated-ci': { shiftType: 'S', note: 'Other employee private note' } } };
  assert.equal((await employmentSave(profileMainData)).status, 200);
  const draftProfile = await (await profileRead('schedule')).json() as any;
  assert.equal(draftProfile.items.find((day: any) => day.date === '2025-03-10').shiftName, 'غير مجدول');
  assert.equal((await publish(mainDataVersion({ schedule: profileMainData.schedule, shiftTypes: profileMainData.shiftTypes }))).status, 200);
  const publishedProfile = await (await profileRead('schedule')).json() as any;
  assert.equal(publishedProfile.items.length, 31);
  assert.equal(publishedProfile.items.find((day: any) => day.date === '2025-03-10').note, 'Profile published note');
  assert.ok(!JSON.stringify(publishedProfile).includes('Other employee private note'));
  assert.ok(publishedProfile.publishedAt);
  console.log('PASS: unified profiles are admin-only, tenant/employee scoped, secret-free, monthly and paginated, and display published schedules only.');
  console.log('PASS: dated transfers are server-owned, survive forged history and profile edits, reject future dates, and store no transient request metadata.');
  console.log('PASS: corrections require valid reason/ownership, preserve originals/untouched fields, approve atomically once, and keep stale or closed-month requests pending.');
  console.log('PASS: inactive accounts cannot login/read/punch/change email or request WebAuthn; archival retains history, restoration works, audit is scoped and secrets are excluded.');
  console.log('PASS: drafts stay private; explicit publish and explicit published clearing update employee schedules/notices without cache reuse, with guarded/idempotent publication and audit.');
  console.log('PASS: schedule analysis, approved leave, rest, overnight absence, grace and potential overtime through HTTP.');
  console.log('PASS: scoped report period/employee/department, whole-day paging, complete export, totals and employee permissions.');
  console.log('PASS: monthly snapshot, closed-month create/update/delete/date-move guards, reopening reason and audit.');
  console.log('PASS: per-employee server geofence, GPS required, duplicate punch serialization, scoped checkout and audit events.');
  console.log('PASS: concurrent saves, stale client rejection, reload-and-save, metadata not persisted.');
} finally {
  child.kill('SIGTERM');
  await pool.end();
}
