import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { promises as fs } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import pg from 'pg';
import jwt from 'jsonwebtoken';
import { welcomeStateKey } from '../src/server/systemHealth';
import { fullAdminAccess } from '../src/lib/adminAccess';
import { emailVerificationKey } from '../src/server/emailVerification';
const directory=await fs.mkdtemp(path.join(tmpdir(),'attendance-health-')),secret='health-ci-only-secret',companyId='health-ci',id='health-employee';
const pool=new pg.Pool({host:process.env.SQL_HOST,port:Number(process.env.SQL_PORT || 5432),user:process.env.SQL_USER,password:process.env.SQL_PASSWORD,database:process.env.SQL_DB_NAME});
const child=spawn(process.execPath,['--import','./tests/mockResend.mjs','dist/server.cjs'],{env:{...process.env,NODE_ENV:'production',JWT_SECRET:secret,BACKUP_ENABLED:'false',BACKUP_DIR:directory,RESEND_API_KEY:'mock-key',RESEND_FROM:'Attendance <attendance@example.com>',APP_URL:'https://attendance.example.com',ATTENDANCE_TEST_EMAIL_CAPTURE:path.join(directory,'mail.jsonl')},stdio:'inherit'});
const origin='http://127.0.0.1:3011';
const headers=(role:string)=>({Authorization:'Bearer '+jwt.sign({role,companyId,...(role==='employee'?{id}:{}),name:'Health CI'},secret,{expiresIn:'1h'}),'Content-Type':'application/json'});
const request=(endpoint:string,role='admin',method='GET')=>fetch(origin+endpoint+'?companyId='+companyId,{method,headers:headers(role),...(method==='POST'?{body:'{}'}:{})});
const put=(key:string,value:any)=>pool.query('INSERT INTO shift_app.system_data (key,value) VALUES ($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value',[key,JSON.stringify(value)]);
try{
 let ready=false;for(let i=0;i<60;i++){try{if((await fetch(origin+'/api/health/live')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,500));}assert.ok(ready);
 const data={employees:[{id,name:'Health Employee',email:'health@example.com',dept:'d'}],departments:[{id:'d',name:'Department'}],shiftTypes:[],schedule:{},settings:{companyName:'Health CI'}};
 await put('mainData_'+companyId,data);
 await put(welcomeStateKey(companyId,id),{status:'failed',startedAt:Date.now()-100000,claimedAt:Date.now()-100000,payload:{from:'Attendance <attendance@example.com>',to:['health@example.com'],subject:'Welcome',text:'private-mail-body'},claim:'private-claim'});
 await put(emailVerificationKey(companyId,id),{email:'health@example.com',delivery:'failed',requestedAt:Date.now(),codeHash:'private-hash',nonce:'private-nonce'});
 assert.equal((await fetch(origin+'/api/system-health?companyId='+companyId)).status,401);assert.equal((await request('/api/system-health','employee')).status,403);
 assert.equal((await fetch(origin+'/api/system-health?companyId=other',{headers:headers('admin')})).status,403);
 const initial=await request('/api/system-health');assert.equal(initial.headers.get('cache-control'),'private, no-store');const report:any=await initial.json();
 assert.equal(report.database.status,'ok');assert.equal(report.database.tables.length,8);assert.equal(report.backup.status,'missing');assert.match(report.version.id,/^[a-f0-9]{16}$/);assert.equal(report.mail.counts.failed,2);assert.equal(report.permissions.canBackup,false);assert.equal(JSON.stringify(report).includes('private-'),false);
 const delegated=await pool.query('INSERT INTO shift_app.admins(name,username,password,company_id) VALUES ($1,$2,$3,$4) RETURNING id',['Health settings admin','health-settings-ci','ci-only-hash',companyId]);
 const delegatedId=delegated.rows[0].id,aclKey='adminAccess:'+companyId+':'+delegatedId;
 const delegatedHeaders={Authorization:'Bearer '+jwt.sign({role:'admin',companyId,id:delegatedId},secret,{expiresIn:'1h'})};
 await put(aclKey,fullAdminAccess());assert.equal((await fetch(origin+'/api/system-health?companyId='+companyId,{headers:delegatedHeaders})).status,200);
 await put(aclKey,{...fullAdminAccess(),departmentIds:['d']});assert.equal((await fetch(origin+'/api/system-health?companyId='+companyId,{headers:delegatedHeaders})).status,403);
 await put(aclKey,{...fullAdminAccess(),permissions:{...fullAdminAccess().permissions,canManageSettings:false}});assert.equal((await fetch(origin+'/api/system-health?companyId='+companyId,{headers:delegatedHeaders})).status,403);
 await fs.writeFile(path.join(directory,'health-errors.json'),JSON.stringify({items:[{companyId:'other',route:'/api/hidden',method:'POST',status:500,at:new Date().toISOString()},{companyId,route:'/api/own',method:'POST',status:503,at:new Date().toISOString(),payload:'private-payload'}]}));
 const scopedErrors:any=await (await request('/api/system-health')).json();assert.equal(scopedErrors.errors.length,1);assert.equal(scopedErrors.errors[0].route,'/api/own');assert.equal(scopedErrors.errors[0].payload,undefined);
 assert.equal((await request('/api/system-health/backup','admin','POST')).status,403);assert.equal((await request('/api/system-health/verify-restore','admin','POST')).status,403);
 const retry='/api/employees/'+id+'/welcome-email';assert.equal((await request(retry,'admin','POST')).status,200);assert.equal((await request(retry,'admin','POST')).status,200);
 const captures=(await fs.readFile(path.join(directory,'mail.jsonl'),'utf8')).trim().split('\n').map(s=>JSON.parse(s));assert.equal(captures.length,1);assert.equal(captures[0].idempotencyKey,welcomeStateKey(companyId,id));
 const accepted:any=await (await request('/api/system-health')).json();assert.equal(accepted.mail.counts.accepted,1);assert.equal(accepted.mail.items.find((r:any)=>r.kind==='welcome').canRetry,false);
 await put(welcomeStateKey(companyId,id),{status:'failed',startedAt:Date.now(),payload:{to:['old@example.com']}});assert.equal((await request(retry,'admin','POST')).status,409);
 await fs.mkdir(path.join(directory,'.backup-lock'));assert.equal((await request('/api/system-health/backup','superadmin','POST')).status,409);await fs.rm(path.join(directory,'.backup-lock'),{recursive:true});
 assert.equal((await request('/api/system-health/backup','superadmin','POST')).status,200);
 const backed:any=await (await request('/api/system-health','superadmin')).json();assert.equal(backed.backup.status,'ok');assert.ok(backed.backup.lastSuccess.bytes>0);assert.match(backed.backup.lastSuccess.sha256,/^[a-f0-9]{64}$/);
 assert.equal((await request('/api/system-health/verify-restore','superadmin','POST')).status,200);
 const verified:any=await (await request('/api/system-health')).json();assert.equal(verified.backup.lastVerification.status,'success');assert.equal(verified.backup.lastVerification.tables,8);
 assert.equal((await pool.query("SELECT datname FROM pg_database WHERE datname LIKE 'attendance_restore_check_%'")).rows.length,0);
 assert.deepEqual((await pool.query('SELECT value FROM shift_app.system_data WHERE key=$1',['mainData_'+companyId])).rows[0].value,data,'health and backups never update live employee data');
 const file=path.join(directory,backed.backup.lastSuccess.name),bytes=await fs.readFile(file);bytes[0]^=1;await fs.writeFile(file,bytes);assert.equal((await request('/api/system-health/verify-restore','superadmin','POST')).status,503);
 assert.equal((await pool.query("SELECT datname FROM pg_database WHERE datname LIKE 'attendance_restore_check_%'")).rows.length,0);
 assert.deepEqual((await pool.query('SELECT value FROM shift_app.system_data WHERE key=$1',['mainData_'+companyId])).rows[0].value,data);
 console.log('PASS: system health enforces company/role access, redacts mail secrets, retries idempotently, creates a real PostgreSQL archive, restores only to a random isolated database, cleans it up and rejects corrupt archives without changing live data.');
}finally{child.kill('SIGTERM');await pool.end();await new Promise(r=>child.exitCode!==null?r(null):child.once('exit',r));await fs.rm(directory,{recursive:true,force:true});}
