import { useEffect, useState, useRef, type PointerEvent, type FormEvent } from 'react';
import { CheckCircle2, XCircle } from 'lucide-react';

function Signature({value,onChange}:{value:string;onChange:(v:string)=>void}) {
  const ref=useRef<HTMLCanvasElement|null>(null), drawing=useRef(false),moved=useRef(false); const [empty,setEmpty]=useState(!value);
  const pos=(e:PointerEvent<HTMLCanvasElement>)=>{const c=ref.current!;const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height};};
  const down=(e:PointerEvent<HTMLCanvasElement>)=>{const c=ref.current!;c.setPointerCapture(e.pointerId);const p=pos(e),ctx=c.getContext('2d')!;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineWidth=2.5;ctx.lineCap='round';drawing.current=true;moved.current=false;};
  const move=(e:PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current)return;const p=pos(e),ctx=ref.current!.getContext('2d')!;ctx.lineTo(p.x,p.y);ctx.stroke();moved.current=true;setEmpty(false);};
  const end=()=>{if(!drawing.current)return;drawing.current=false;if(moved.current)onChange(ref.current!.toDataURL('image/png'));};
  const clear=()=>{const c=ref.current!;c.getContext('2d')!.clearRect(0,0,c.width,c.height);setEmpty(true);onChange('');};
  return <div><div className="flex justify-between text-xs font-bold mb-1"><span>توقيع المدير</span><button type="button" onClick={clear} className="text-rose-600 text-[10px]">مسح</button></div><canvas ref={ref} width={640} height={180} onPointerDown={down} onPointerMove={move} onPointerUp={end} onPointerCancel={end} className="w-full h-32 bg-white border-2 border-dashed rounded-xl touch-none"/>{empty&&<div className="text-[10px] text-slate-400 mt-1">وقّع داخل المربع</div>}</div>;
}
const label=(v:string)=>({temporary_exit:'استئذان (خروج مؤقت)',early_exit:'خروج مبكر',late_arrival:'تأخير عن الدوام',absence:'غياب عن الدوام'} as Record<string,string>)[v]||v;
export default function DocumentApprovalPage({token}:{token:string}) {
  const [doc,setDoc]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[managerName,setManagerName]=useState(''),[signature,setSignature]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState<any>(null);
  const [managerToken,setManagerToken]=useState(''),[needsLogin,setNeedsLogin]=useState(false),[username,setUsername]=useState(''),[password,setPassword]=useState('');
  const authHeaders=managerToken?{Authorization:'Bearer '+managerToken}:{};
  const login=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth/admin-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const j=await r.json();if(!r.ok)throw new Error(j.error||'تعذر تسجيل الدخول');setPassword('');setManagerToken(j.token);}catch(e:any){setError(e.message);}finally{setBusy(false)}};
  const load=async(signal:AbortSignal)=>{setLoading(true);setError('');setDoc(null);try{const r=await fetch('/api/document-approval/'+encodeURIComponent(token),{headers:authHeaders,signal});const j=await r.json();if(signal.aborted)return;if(r.status===401||r.status===403){setNeedsLogin(true);setError(j.error||'سجّل الدخول بحساب مدير مخوّل');return;}if(!r.ok)throw new Error(j.error||'الرابط غير صالح');setNeedsLogin(false);setManagerName(j.managerName||'المدير');setDoc(j);}catch(e:any){if(!signal.aborted)setError(e.message)}finally{if(!signal.aborted)setLoading(false)}};
  useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort();},[token,managerToken]);
  const decide=async(decision:'approved'|'rejected')=>{if(!managerName||!signature){alert('أدخل اسم المدير والتوقيع.');return;}if(decision==='rejected'&&!reason.trim()){alert('اكتب سبب الرفض.');return;}setBusy(true);try{const r=await fetch('/api/document-approval/'+encodeURIComponent(token),{method:'POST',headers:{'Content-Type':'application/json',...authHeaders},body:JSON.stringify({managerSignature:signature,decision,reason})});const j=await r.json();if(!r.ok)throw new Error(j.error||'تعذر تنفيذ القرار');setDone(j);}catch(e:any){alert(e.message)}finally{setBusy(false)}};
  if(loading)return <div dir="rtl" className="min-h-screen bg-slate-50 flex items-center justify-center text-sm text-slate-500">جاري تحميل المستند...</div>;
  if(needsLogin)return <div dir="rtl" className="min-h-screen bg-slate-50 flex items-center justify-center p-4"><form onSubmit={login} className="max-w-md w-full bg-white border rounded-2xl p-6 space-y-4"><h1 className="font-black">دخول المدير لاعتماد الاستئذان</h1><p className="text-sm text-slate-500">استخدم حساب إدارة الشركة أو مدير القسم الذي لديه صلاحية اعتماد الطلبات.</p>{error&&<p role="alert" className="text-sm text-rose-600">{error}</p>}<label className="block text-sm">اسم المستخدم أو البريد<input required autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} className="mt-1 w-full border rounded-lg p-2"/></label><label className="block text-sm">كلمة المرور<input required type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 w-full border rounded-lg p-2"/></label><button disabled={busy} className="w-full py-3 rounded-xl bg-sky-600 text-white font-bold">{busy?'جاري الدخول…':'دخول ومراجعة الطلب'}</button></form></div>;
  if(error)return <div dir="rtl" className="min-h-screen bg-slate-50 flex items-center justify-center p-4"><div className="max-w-md bg-white border rounded-2xl p-6 text-center"><XCircle className="mx-auto text-rose-500 mb-3"/><h1 className="font-black">الرابط غير متاح</h1><p className="text-sm text-slate-500 mt-2">{error}</p></div></div>;
  if(done)return <div dir="rtl" className="min-h-screen bg-slate-50 flex items-center justify-center p-4"><div className="max-w-md bg-white border rounded-2xl p-7 text-center"><CheckCircle2 className="mx-auto text-emerald-500 mb-3" size={44}/><h1 className="font-black text-lg">{done.status==='approved'?'تم اعتماد المستند':'تم تسجيل رفض المستند'}</h1><p className="text-sm text-slate-500 mt-2">تم إغلاق رابط الاعتماد ولا يمكن استخدامه مرة أخرى.</p></div></div>;
  const f=doc.formData||{};
  return <div dir="rtl" className="min-h-screen bg-slate-100 py-6 px-3"><div className="max-w-3xl mx-auto bg-white rounded-2xl shadow-sm border overflow-hidden">
    <div className="p-5 border-b text-center">{doc.logoDataUrl&&<img src={doc.logoDataUrl} className="max-h-16 max-w-48 mx-auto object-contain"/>}<h1 className="font-black text-lg mt-2">{doc.companyName||'الشركة'}</h1><h2 className="font-black text-xl mt-5">نموذج استئذان — اعتماد الإدارة</h2><p className="text-[10px] text-slate-400 mt-1">الرابط صالح حتى {new Date(doc.expiresAt).toLocaleString('ar-SA-u-ca-gregory-nu-latn')}</p></div>
    <div className="p-5"><div className="grid sm:grid-cols-2 gap-3 text-xs"><div className="border rounded-xl p-3"><b>اسم الموظف:</b> {doc.employeeName}</div><div className="border rounded-xl p-3"><b>القسم:</b> {doc.departmentName||'—'}</div><div className="border rounded-xl p-3"><b>التاريخ:</b> {f.date||'—'}</div><div className="border rounded-xl p-3"><b>نوع الطلب:</b> {label(f.requestType)}</div>{f.requestType==='absence'&&<div className="border rounded-xl p-3"><b>نوع الغياب:</b> {({annual:'إجازة سنوية',sick:'إجازة مرضية',other:'أخرى'} as Record<string,string>)[f.absenceType]||f.absenceType}</div>}{f.exitTime&&<div className="border rounded-xl p-3"><b>وقت الخروج:</b> {f.exitTime}</div>}{f.expectedReturnTime&&<div className="border rounded-xl p-3"><b>العودة المتوقعة:</b> {f.expectedReturnTime}</div>}{f.actualAttendanceTime&&<div className="border rounded-xl p-3"><b>الحضور الفعلي:</b> {f.actualAttendanceTime}</div>}{f.absenceFrom&&<div className="border rounded-xl p-3"><b>من:</b> {f.absenceFrom} <b>إلى:</b> {f.absenceTo}</div>}<div className="sm:col-span-2 border rounded-xl p-3"><b>سبب الطلب:</b><div className="whitespace-pre-wrap mt-2">{f.reason}</div></div></div>
    <div className="mt-6 border-t pt-5"><h3 className="font-black text-sm mb-3">توقيع واعتماد المدير</h3><label className="text-xs font-bold">اسم المدير<input value={managerName} readOnly className="mt-1 w-full border rounded-lg p-2"/></label><div className="mt-3"><Signature value={signature} onChange={setSignature}/></div><label className="block text-xs font-bold mt-3">ملاحظات القرار<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3} className="mt-1 w-full border rounded-lg p-2" placeholder="مطلوب عند الرفض"/></label>
    <div className="grid sm:grid-cols-2 gap-3 mt-5"><button disabled={busy} onClick={()=>decide('approved')} className="py-3 rounded-xl bg-emerald-600 text-white font-black text-sm flex items-center justify-center gap-2"><CheckCircle2 size={17}/> اعتماد المستند</button><button disabled={busy} onClick={()=>decide('rejected')} className="py-3 rounded-xl bg-rose-600 text-white font-black text-sm flex items-center justify-center gap-2"><XCircle size={17}/> رفض المستند</button></div></div></div>
  </div></div>;
}
