import { useEffect, useState } from 'react';
import { formatMinutes, formatPunch } from '../lib/attendanceReport';
export default function EmployeeAttendanceHistory({companyId,refreshKey}:{companyId:string;refreshKey:string}) {
  const [month,setMonth]=useState(()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Riyadh'}).slice(0,7)),[filter,setFilter]=useState('all'),[report,setReport]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[reload,setReload]=useState(0);
  useEffect(()=>{
    const controller=new AbortController();setLoading(true);setReport(null);setError('');
    fetch('/api/employee-attendance?'+new URLSearchParams({companyId,month}),{signal:controller.signal,cache:'no-store'}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error || 'تعذر تحميل الكشف');if(!controller.signal.aborted)setReport(data);}).catch(e=>{if(!controller.signal.aborted)setError(e.message || 'تعذر الاتصال');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
    return()=>controller.abort();
  },[companyId,month,reload,refreshKey]);
  const items=(report?.items || []).filter((day:any)=>filter==='absent'?day.absent:filter==='review'?day.needsReview:true);
  return <section dir="rtl" className="wafr-attendance-history flex flex-col gap-4">
    <div className="bg-white p-4 rounded-xl border flex flex-wrap items-center gap-3"><h2 className="font-bold flex-1">بصماتي وأيام الغياب</h2><label className="text-sm">الشهر<input aria-label="شهر كشف البصمات" type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}} className="border p-2 rounded mr-2" /></label><button disabled={loading} onClick={()=>setReload(n=>n+1)} className="text-sm p-2 rounded bg-sky-100 text-sky-800 disabled:opacity-50">تحديث الكشف</button></div>
    <p className="text-xs text-slate-500">الغياب محسوب من جدولك المنشور بعد انتهاء الشيفت، مع استبعاد الإجازات المعتمدة والراحة. النتائج للمراجعة ولا تعد قرار خصم. الساعات بين أول حضور وآخر انصراف؛ الفترات المزدوجة والبصمات الناقصة تحتاج مراجعة.</p>
    {loading&&<p role="status">جاري تحميل كشفك…</p>}{error&&<p role="alert" className="p-4 bg-rose-50 text-rose-700 rounded">{error}</p>}
    {report&&<><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{[['ساعات مسجلة',formatMinutes(report.totalMinutes)],['أيام غياب',report.absentDays],['أيام تأخير',report.lateDays],['تحتاج مراجعة',report.reviewDays]].map(([label,value])=><div key={label} className="p-4 bg-white rounded-xl border"><p className="text-xs text-slate-500">{label}</p><strong className="block text-xl mt-2">{value}</strong></div>)}</div>
    <label className="text-sm">عرض<select value={filter} onChange={e=>setFilter(e.target.value)} className="p-2 border rounded bg-white mr-2"><option value="all">كل الأيام</option><option value="absent">أيام الغياب فقط</option><option value="review">البصمات التي تحتاج مراجعة</option></select></label>
    <div className="flex flex-col gap-3">{items.length===0?<p className="bg-white border p-5 rounded-xl">لا توجد أيام مطابقة للفترة والفلتر المحددين.</p>:items.map((day:any)=><article key={day.date} className={'bg-white border rounded-xl p-4 '+(day.absent?'border-rose-200':'border-sky-100')}><div className="flex flex-wrap justify-between gap-2 mb-3"><strong>{new Date(day.date+'T12:00:00+03:00').toLocaleDateString('ar-SA',{timeZone:'Asia/Riyadh',weekday:'long',day:'numeric',month:'long',numberingSystem:'latn'})}</strong><span className={day.absent?'text-rose-700':'text-slate-600'}>{day.status}</span></div><dl className="grid grid-cols-2 sm:grid-cols-3 gap-3 text-sm"><div><dt className="text-slate-500">أول حضور</dt><dd className="font-bold">{formatPunch(day.first)}</dd><dd className="text-xs mt-1">{day.first?.location || '—'}</dd></div><div><dt className="text-slate-500">آخر انصراف</dt><dd className="font-bold">{formatPunch(day.last)}</dd><dd className="text-xs mt-1">{day.last?.location || '—'}</dd></div><div><dt className="text-slate-500">الساعات المسجلة</dt><dd className="font-bold">{formatMinutes(day.minutes)}</dd>{day.lateMinutes>0&&<dd className="text-xs text-amber-700">تأخير {day.lateMinutes} دقيقة</dd>}</div></dl></article>)}</div><p className="text-xs text-slate-500">آخر تحديث: {new Date(report.generatedAt).toLocaleString('ar-SA',{timeZone:'Asia/Riyadh',numberingSystem:'latn'})}</p></>}
  </section>;
}
