import DocumentPrintDialog, { useDocumentPrint } from '../../components/DocumentPrintDialog';
import { useEffect, useState } from 'react';
import { Printer, RefreshCw, Ban, Link2 } from 'lucide-react';

const statusLabel=(s:string)=>({employee_signed:'بانتظار موافقة الإدارة',manager_ready:'موافق عليه — الرابط متاح للموظف',admin_rejected:'مرفوض من الإدارة',pending_manager:'بانتظار اعتماد المدير',approved:'معتمد',rejected:'مرفوض',cancelled:'ملغي'} as Record<string,string>)[s]||s;
const statusClass=(s:string)=>s==='approved'?'bg-emerald-50 text-emerald-700':s==='rejected'||s==='admin_rejected'||s==='cancelled'?'bg-rose-50 text-rose-700':s==='pending_manager'?'bg-amber-50 text-amber-700':'bg-sky-50 text-sky-700';
export default function ElectronicDocumentsView({companyId}:{companyId:string}) {
 const {html,printDocument:print,closePrint}=useDocumentPrint(companyId);
 const [reviewBusy,setReviewBusy]=useState<number|null>(null);
 const [selected,setSelected]=useState<any>(null);
 const [docs,setDocs]=useState<any[]>([]),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/electronic-documents?companyId='+encodeURIComponent(companyId)+'&scope=admin');if(r.ok)setDocs(await r.json());}finally{setLoading(false);}};
 useEffect(()=>{void load();const timer=setInterval(()=>{if(!document.hidden)void load();},60000);return()=>clearInterval(timer);},[companyId]);
 const review=async(id:number,decision:'approved'|'rejected')=>{
  const reason=decision==='rejected'?window.prompt('سبب رفض الإدارة:'):'';
  if(reason===null)return;
  if(decision==='rejected'&&!reason?.trim()){alert('سبب الرفض مطلوب');return;}
  setReviewBusy(id);
  try{const r=await fetch('/api/electronic-documents/'+id+'/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId,decision,reason})});const j=await r.json();if(!r.ok)throw new Error(j.error||'تعذر مراجعة الطلب');await load();}catch(e:any){alert(e.message);}finally{setReviewBusy(null);}
 };
 const cancel=async(id:number)=>{if(!confirm('هل تريد إلغاء هذا المستند؟'))return;const r=await fetch('/api/electronic-documents/'+id+'/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId,status:'cancelled'})});if(!r.ok){const j=await r.json().catch(()=>({}));alert(j.error||'تعذر الإلغاء');return;}await load();};
 return <div dir="rtl" className="flex flex-col gap-5">{html&&<DocumentPrintDialog html={html} onClose={closePrint}/>}
  <div className="flex items-center justify-between gap-3"><div><h2 className="font-black text-lg">المستندات الإلكترونية</h2><p className="text-xs text-slate-500 mt-1">راجع طلب الموظف أولًا؛ بعد موافقة الإدارة يتاح له رابط إرساله للمدير للتوقيع. الاعتماد يحفظ المستند ولا يغيّر حساب الحضور أو الخصومات تلقائيًا.</p></div><button onClick={()=>void load()} className="p-2 border rounded-lg"><RefreshCw size={16}/></button></div>
  {selected&&<div className="fixed inset-0 z-[90] bg-black/40 flex items-center justify-center p-3"><div className="bg-white rounded-2xl p-5 w-full max-w-xl max-h-[90dvh] overflow-y-auto"><div className="flex justify-between mb-4"><h3 className="font-bold">تفاصيل المستند #{selected.id}</h3><button onClick={()=>setSelected(null)}>إغلاق</button></div><dl className="space-y-3 text-sm">{[['الموظف',selected.employeeName],['القسم',selected.departmentName],['الحالة',statusLabel(selected.status)],['نوع الطلب',({temporary_exit:'خروج مؤقت',early_exit:'خروج مبكر',late_arrival:'تأخير',absence:'غياب'} as Record<string,string>)[selected.formData?.requestType]],['نوع الغياب',({annual:'سنوية',sick:'مرضية',other:'أخرى'} as Record<string,string>)[selected.formData?.absenceType]],['التاريخ',selected.formData?.date],['وقت الخروج',selected.formData?.exitTime],['وقت العودة',selected.formData?.expectedReturnTime],['وقت الحضور',selected.formData?.actualAttendanceTime],['من',selected.formData?.absenceFrom],['إلى',selected.formData?.absenceTo],['السبب',selected.formData?.reason],['المدير',selected.managerName],['ملاحظات القرار',selected.reviewReason]].filter(([,value])=>value).map(([key,value])=><div key={key}><dt className="font-bold">{key}</dt><dd className="whitespace-pre-wrap">{value}</dd></div>)}</dl></div></div>}
  <div className="bg-white border rounded-2xl overflow-hidden">{loading?<div className="p-10 text-center text-sm text-slate-400">جاري التحميل...</div>:docs.length===0?<div className="p-10 text-center text-sm text-slate-400">لا توجد مستندات إلكترونية.</div>:<div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50"><tr>{['المستند','الموظف','القسم','التاريخ','الحالة','الإجراء'].map(h=><th key={h} className="p-3 text-right">{h}</th>)}</tr></thead><tbody>{docs.map(d=><tr key={d.id} className="border-t"><td className="p-3 font-bold">استئذان #{d.id}</td><td className="p-3">{d.employeeName}</td><td className="p-3">{d.departmentName||'—'}</td><td className="p-3">{d.formData?.date||'—'}</td><td className="p-3"><span className={'px-2.5 py-1 rounded-full font-bold '+statusClass(d.status)}>{statusLabel(d.status)}</span></td><td className="p-3"><div className="flex gap-2"><button onClick={()=>setSelected(d)} className="px-3 py-1.5 border rounded-lg font-bold">التفاصيل</button>{d.status==='employee_signed'&&<><button disabled={reviewBusy===d.id} onClick={()=>void review(d.id,'approved')} className="px-3 py-1.5 border border-emerald-200 text-emerald-700 rounded-lg font-bold">موافقة الإدارة</button><button disabled={reviewBusy===d.id} onClick={()=>void review(d.id,'rejected')} className="px-3 py-1.5 border border-rose-200 text-rose-700 rounded-lg font-bold">رفض</button></>}{d.status==='approved'&&<button onClick={()=>print(d)} className="px-3 py-1.5 border rounded-lg font-bold"><Printer size={13} className="inline ml-1"/>طباعة</button>}{(d.status==='employee_signed'||d.status==='manager_ready'||d.status==='pending_manager')&&<button onClick={()=>void cancel(d.id)} className="px-3 py-1.5 border border-rose-200 text-rose-600 rounded-lg font-bold"><Ban size={13} className="inline ml-1"/>إلغاء</button>}</div></td></tr>)}</tbody></table></div>}</div>
 </div>;
}
