import DocumentPrintDialog, { useDocumentPrint } from '../../components/DocumentPrintDialog';
import { useEffect, useState } from 'react';
import { Printer, RefreshCw, Ban, Link2 } from 'lucide-react';

const statusLabel=(s:string)=>({employee_signed:'اعتمده الموظف',manager_ready:'موافق عليه — الرابط متاح للموظف',admin_rejected:'مرفوض من الإدارة',pending_manager:'بانتظار اعتماد المدير',approved:'معتمد',rejected:'مرفوض',cancelled:'ملغي'} as Record<string,string>)[s]||s;
const statusClass=(s:string)=>s==='approved'?'bg-emerald-50 text-emerald-700':s==='rejected'||s==='admin_rejected'||s==='cancelled'?'bg-rose-50 text-rose-700':s==='pending_manager'?'bg-amber-50 text-amber-700':'bg-sky-50 text-sky-700';
export default function ElectronicDocumentsView({companyId}:{companyId:string}) {
 const {html,printDocument:print,closePrint}=useDocumentPrint(companyId);
 const [reviewBusy,setReviewBusy]=useState<number|null>(null);
 const [selected,setSelected]=useState<any>(null);
 const [docs,setDocs]=useState<any[]>([]),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/electronic-documents?companyId='+encodeURIComponent(companyId)+'&scope=admin');if(r.ok)setDocs(await r.json());}finally{setLoading(false);}};
 useEffect(()=>{void load();const timer=setInterval(()=>{if(!document.hidden)void load();},60000);return()=>clearInterval(timer);},[companyId]);
 const [timeline,setTimeline]=useState<any[]>([]);
 useEffect(()=>{
  if(!selected){setTimeline([]);return;}
  const controller=new AbortController();
  fetch('/api/electronic-documents/'+selected.id+'/audit?companyId='+encodeURIComponent(companyId),{signal:controller.signal}).then(r=>r.ok?r.json():[]).then(rows=>{if(!controller.signal.aborted)setTimeline(rows);}).catch(()=>{});
  return()=>controller.abort();
 },[selected?.id,companyId]);
 const remove=async(id:number)=>{
  if(!confirm('حذف الطلب نهائيًا حتى لو معتمد؟ سيُبطل رابط المدير وتُزال علامة الاستئذان من الجدول.'))return;
  try{const r=await fetch('/api/electronic-documents/'+id+'?companyId='+encodeURIComponent(companyId),{method:'DELETE'});const j=await r.json();if(!r.ok)throw new Error(j.error||'تعذر الحذف');setSelected(null);await load();}catch(e:any){alert(e.message);}
 };
 return <div dir="rtl" className="flex flex-col gap-5">{html&&<DocumentPrintDialog html={html} onClose={closePrint}/>}
  <div className="flex items-center justify-between gap-3"><div><h2 className="font-black text-lg">المستندات الإلكترونية</h2><p className="text-xs text-slate-500 mt-1">متابعة اعتماد الموظف ومشاركة الرابط وتوقيع المدير والطباعة. يمكن حذف الطلب حتى بعد اعتماده. الاعتماد يحفظ المستند ولا يغيّر حساب الحضور أو الخصومات تلقائيًا.</p></div><button onClick={()=>void load()} className="p-2 border rounded-lg"><RefreshCw size={16}/></button></div>
  {selected&&<div className="fixed inset-0 z-[90] bg-black/40 flex items-center justify-center p-3"><div className="bg-white rounded-2xl p-5 w-full max-w-xl max-h-[90dvh] overflow-y-auto"><div className="flex justify-between mb-4"><h3 className="font-bold">تفاصيل المستند #{selected.id}</h3><button onClick={()=>setSelected(null)}>إغلاق</button></div><dl className="space-y-3 text-sm">{[['الموظف',selected.employeeName],['القسم',selected.departmentName],['الحالة',statusLabel(selected.status)],['نوع الطلب',({temporary_exit:'خروج مؤقت',early_exit:'خروج مبكر',late_arrival:'تأخير',absence:'غياب'} as Record<string,string>)[selected.formData?.requestType]],['نوع الغياب',({annual:'سنوية',sick:'مرضية',other:'أخرى'} as Record<string,string>)[selected.formData?.absenceType]],['التاريخ',selected.formData?.date],['وقت الخروج',selected.formData?.exitTime],['وقت العودة',selected.formData?.expectedReturnTime],['وقت الحضور',selected.formData?.actualAttendanceTime],['من',selected.formData?.absenceFrom],['إلى',selected.formData?.absenceTo],['السبب',selected.formData?.reason],['المدير',selected.managerName],['ملاحظات القرار',selected.reviewReason]].filter(([,value])=>value).map(([key,value])=><div key={key}><dt className="font-bold">{key}</dt><dd className="whitespace-pre-wrap">{value}</dd></div>)}</dl><h4 className="font-bold mt-5 mb-2">مراحل الطلب</h4><ol className="space-y-2 text-xs">{timeline.map(event=><li key={event.id} className="border rounded-lg p-2"><b>{({employee_signed:'اعتماد الموظف',shared_with_manager:'إتاحة / مشاركة رابط المدير',approved:'اعتماد وتوقيع المدير',rejected:'رفض المدير',print_preview:'فتح نسخة الطباعة',cancelled:'إلغاء الطلب',admin_approved:'موافقة الإدارة السابقة'} as Record<string,string>)[event.action]||event.action}</b><div>{new Date(event.createdAt).toLocaleString('ar-SA-u-ca-gregory-nu-latn')} · {event.actorRole==='manager'?'المدير':event.actorRole==='employee'?'الموظف':'الإدارة'} {event.actorId}</div></li>)}</ol></div></div>}
  <div className="bg-white border rounded-2xl overflow-hidden">{loading?<div className="p-10 text-center text-sm text-slate-400">جاري التحميل...</div>:docs.length===0?<div className="p-10 text-center text-sm text-slate-400">لا توجد مستندات إلكترونية.</div>:<div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50"><tr>{['المستند','الموظف','القسم','التاريخ','الحالة','الإجراء'].map(h=><th key={h} className="p-3 text-right">{h}</th>)}</tr></thead><tbody>{docs.map(d=><tr key={d.id} className="border-t"><td className="p-3 font-bold">استئذان #{d.id}</td><td className="p-3">{d.employeeName}</td><td className="p-3">{d.departmentName||'—'}</td><td className="p-3">{d.formData?.date||'—'}</td><td className="p-3"><span className={'px-2.5 py-1 rounded-full font-bold '+statusClass(d.status)}>{statusLabel(d.status)}</span></td><td className="p-3"><div className="flex gap-2"><button onClick={()=>setSelected(d)} className="px-3 py-1.5 border rounded-lg font-bold">التفاصيل</button>{<button onClick={()=>print(d)} className="px-3 py-1.5 border rounded-lg font-bold"><Printer size={13} className="inline ml-1"/>طباعة</button>}<button onClick={()=>void remove(d.id)} className="px-3 py-1.5 border border-rose-200 text-rose-600 rounded-lg font-bold">حذف الطلب</button></div></td></tr>)}</tbody></table></div>}</div>
 </div>;
}
