import { useEffect, useState } from 'react';
import { Printer, RefreshCw, Ban } from 'lucide-react';

const statusLabel=(s:string)=>({employee_signed:'موقّع من الموظف',pending_manager:'بانتظار اعتماد المدير',approved:'معتمد',rejected:'مرفوض',cancelled:'ملغي'} as Record<string,string>)[s]||s;
const statusClass=(s:string)=>s==='approved'?'bg-emerald-50 text-emerald-700':s==='rejected'||s==='cancelled'?'bg-rose-50 text-rose-700':s==='pending_manager'?'bg-amber-50 text-amber-700':'bg-sky-50 text-sky-700';
export default function ElectronicDocumentsView({companyId}:{companyId:string}) {
 const [docs,setDocs]=useState<any[]>([]),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/electronic-documents?companyId='+encodeURIComponent(companyId)+'&scope=admin');if(r.ok)setDocs(await r.json());}finally{setLoading(false);}};
 useEffect(()=>{void load();},[companyId]);
 const print=(d:any)=>{const w=window.open('','_blank','width=900,height=1000');if(!w)return;w.document.write(d.finalHtml||'<p>لا توجد نسخة قابلة للطباعة.</p>');w.document.close();w.focus();setTimeout(()=>w.print(),300);};
 const cancel=async(id:number)=>{if(!confirm('هل تريد إلغاء هذا المستند؟'))return;const r=await fetch('/api/electronic-documents/'+id+'/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId,status:'cancelled'})});if(!r.ok){const j=await r.json().catch(()=>({}));alert(j.error||'تعذر الإلغاء');return;}await load();};
 return <div dir="rtl" className="flex flex-col gap-5">
  <div className="flex items-center justify-between gap-3"><div><h2 className="font-black text-lg">المستندات الإلكترونية</h2><p className="text-xs text-slate-500 mt-1">طلبات الموظفين الموقعة وروابط اعتماد المدير والنسخ النهائية المحفوظة.</p></div><button onClick={()=>void load()} className="p-2 border rounded-lg"><RefreshCw size={16}/></button></div>
  <div className="bg-white border rounded-2xl overflow-hidden">{loading?<div className="p-10 text-center text-sm text-slate-400">جاري التحميل...</div>:docs.length===0?<div className="p-10 text-center text-sm text-slate-400">لا توجد مستندات إلكترونية.</div>:<div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50"><tr>{['المستند','الموظف','القسم','التاريخ','الحالة','الإجراء'].map(h=><th key={h} className="p-3 text-right">{h}</th>)}</tr></thead><tbody>{docs.map(d=><tr key={d.id} className="border-t"><td className="p-3 font-bold">استئذان #{d.id}</td><td className="p-3">{d.employeeName}</td><td className="p-3">{d.departmentName||'—'}</td><td className="p-3">{d.formData?.date||'—'}</td><td className="p-3"><span className={'px-2.5 py-1 rounded-full font-bold '+statusClass(d.status)}>{statusLabel(d.status)}</span></td><td className="p-3"><div className="flex gap-2">{d.status==='approved'&&<button onClick={()=>print(d)} className="px-3 py-1.5 border rounded-lg font-bold"><Printer size={13} className="inline ml-1"/>طباعة</button>}{d.status!=='approved'&&d.status!=='cancelled'&&<button onClick={()=>void cancel(d.id)} className="px-3 py-1.5 border border-rose-200 text-rose-600 rounded-lg font-bold"><Ban size={13} className="inline ml-1"/>إلغاء</button>}</div></td></tr>)}</tbody></table></div>}</div>
 </div>;
}
