import { useEffect, useState } from 'react';
const time = (value?: string) => value ? new Date(value).toLocaleString('ar-SA', { timeZone:'Asia/Riyadh',calendar:'gregory' }) : 'غير مسجل';
const statusLabel:Record<string,string>={ok:'سليم',unavailable:'تعذر الاتصال',incomplete:'جداول ناقصة',missing:'لا توجد نسخة مسجلة',invalid:'ملف النسخة يحتاج مراجعة',stale:'نسخة قديمة',success:'ناجح',failed:'فشل',running:'جارٍ التنفيذ',accepted:'مقبولة لدى Resend',pending:'غير مؤكد / جارٍ الإرسال'};
export default function SystemHealthView({companyId}:{companyId:string}) {
  const [report,setReport]=useState<any>(null),[loading,setLoading]=useState(false),[action,setAction]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch('/api/system-health?'+new URLSearchParams({companyId}),{signal:controller.signal}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error || 'تعذر تحميل صحة النظام');if(!controller.signal.aborted)setReport(data);}).catch(error=>{if(!controller.signal.aborted)setError(error.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[companyId,refresh]);
  const run=async(endpoint:string,label:string)=>{if(action)return;setAction(endpoint);setError('');setNotice('');try{const response=await fetch(endpoint+'?'+new URLSearchParams({companyId}),{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const data=await response.json();if(!response.ok)throw new Error(data.error || 'تعذر تأكيد العملية');setNotice(label);setRefresh(v=>v+1);}catch(error:any){setError(error.message || 'تعذر تأكيد العملية؛ حدّث الحالة لمعرفة النتيجة');setRefresh(v=>v+1);}finally{setAction('');}};
  const entry = document.querySelector<HTMLScriptElement>('script[type="module"][src]')?.getAttribute('src');
  const clientPath=entry?new URL(entry,location.href).pathname:null;
  const matches=report?.version.entryAssets.length && clientPath ? report.version.entryAssets.includes(clientPath) : null;
  return <div className="space-y-4 min-w-0" dir="rtl">
    <div className="bg-white border rounded-2xl p-4 flex flex-wrap justify-between gap-3 items-center"><div><h2 className="font-bold">صحة النظام والنسخ الاحتياطية</h2><p className="text-xs text-slate-500 mt-1">الفحص عند فتح الصفحة أو طلب التحديث. آخر فحص: {time(report?.generatedAt)}</p></div><button disabled={loading || !!action} className="border rounded-lg px-4 py-2 text-xs disabled:opacity-50" onClick={()=>setRefresh(v=>v+1)}>{loading?'جارٍ الفحص…':'تحديث الحالة'}</button></div>
    {error && <p role="alert" className="bg-rose-50 text-rose-700 p-3 rounded-xl text-sm">{error}</p>}{notice && <p role="status" className="bg-emerald-50 text-emerald-700 p-3 rounded-xl text-sm">{notice}</p>}{action && <p className="text-xs bg-sky-50 text-sky-800 p-3 rounded-xl">العملية جارية، وقد تستغرق بضع دقائق. يمكنك متابعة نتيجتها من حالة النظام بعد انتهائها.</p>}
    {report && <>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <section className="bg-white border rounded-xl p-4 space-y-3"><h3 className="font-bold text-sm">قاعدة البيانات</h3><p className={`text-sm ${report.database.status==='ok'?'text-emerald-700':'text-rose-700'}`}>{statusLabel[report.database.status]} · {report.database.message}</p><p className="text-xs text-slate-500">مدة فحص الاتصال والجداول: {report.database.latencyMs ?? '—'} ms</p><div className="flex flex-wrap gap-2">{report.database.tables.map((table:any)=><span key={table.name} className={`rounded px-2 py-1 text-xs ${table.present?'bg-emerald-50':'bg-rose-50'}`}>{table.name}: {table.present?'موجود':'ناقص'}</span>)}</div></section>
        <section className="bg-white border rounded-xl p-4 space-y-3"><h3 className="font-bold text-sm">إصدار التطبيق</h3><p className="text-sm font-mono break-all">{report.version.id}</p><p className="text-xs">وقت البناء: {time(report.version.builtAt)}{report.version.commit && <span> · {report.version.commit}</span>}</p><p className={`text-xs ${matches===false?'text-amber-700':'text-slate-500'}`}>{matches===null?'لا تتوفر مقارنة إصدار الواجهة في هذه البيئة':matches?'الواجهة المفتوحة تطابق إصدار السيرفر':'الواجهة المفتوحة قديمة؛ استخدم إشعار تحديث التطبيق لإحضار الإصدار الجديد'}</p></section>
      </div>
      <section className="bg-white border rounded-xl p-4 space-y-3"><h3 className="font-bold text-sm">النسخ الاحتياطية</h3><p className={`text-sm ${report.backup.status==='ok'?'text-emerald-700':'text-amber-700'}`}>{statusLabel[report.backup.status]} · النسخ اليومي {report.backup.enabled?'مفعّل':'غير مفعّل'}</p><p className="text-xs text-slate-500">نسخة محلية لمخطط تطبيق الحضور بكل شركاته، آخر 14 نسخة محفوظة. احتفظ بنسخة مستقلة خارج السيرفر أيضًا.</p>{report.backup.lastSuccess && <div className="text-xs space-y-1"><p>آخر نجاح: {time(report.backup.lastSuccess.createdAt)} · {(report.backup.lastSuccess.bytes/1024/1024).toFixed(2)} MB</p><p className="break-all font-mono">{report.backup.lastSuccess.name}</p><p>فحص بنية الأرشيف عند الإنشاء: {report.backup.lastSuccess.archiveVerified?'نجح':'غير مؤكد'}</p></div>}<p className="text-xs">آخر محاولة: {statusLabel[report.backup.lastAttempt?.status] || 'غير مسجلة'} · {time(report.backup.lastAttempt?.at)} · {report.backup.lastAttempt?.message}</p><p className="text-xs">اختبار الاسترجاع: {statusLabel[report.backup.lastVerification?.status] || 'لم يُجرَ'} · {time(report.backup.lastVerification?.at)} · {report.backup.lastVerification?.message}</p>{report.backup.lastVerification?.cleanupRequired && <p role="alert" className="text-xs text-rose-700">يلزم حذف قاعدة الاختبار بواسطة مسؤول PostgreSQL: {report.backup.lastVerification.testDatabase}</p>}{report.backup.lastVerification?.backupName && <p className="text-xs text-slate-500 break-all">النسخة التي اختُبرت: {report.backup.lastVerification.backupName}</p>}
        {report.permissions.canBackup && <div className="flex flex-wrap gap-2 text-xs"><button disabled={!!action || loading} onClick={()=>run('/api/system-health/backup','تم إنشاء النسخة وفحص بنية الأرشيف')} className="bg-sky-600 text-white rounded-lg px-4 py-2 disabled:opacity-50">إنشاء نسخة الآن</button><button disabled={!!action || loading || !report.backup.lastSuccess || report.backup.status==='invalid'} onClick={()=>{if(window.confirm('سيتم إنشاء قاعدة مؤقتة مستقلة، واسترجاع النسخة فيها ثم حذفها. يلزم أن يملك مستخدم PostgreSQL صلاحية إنشاء قواعد البيانات. ابدأ الفحص؟'))void run('/api/system-health/verify-restore','نجح اختبار الاسترجاع وتم حذف القاعدة المؤقتة');}} className="border rounded-lg px-4 py-2 disabled:opacity-50">اختبار الاسترجاع</button></div>}
      </section>
      <section className="bg-white border rounded-xl p-4 space-y-3"><h3 className="font-bold text-sm">إرسال الإيميلات</h3><p className="text-xs">إعداد Resend: {report.mail.configured?'متوفر':'ناقص'} · {report.mail.available?'آخر حالة لكل موظف ونوع رسالة':'تعذر قراءة حالات البريد'}</p><p className="text-xs text-slate-500">قبول Resend لا يؤكد وصول الرسالة لصندوق الموظف؛ التسليم والارتداد يُراجعان من لوحة Resend. رموز التأكيد الجديدة يطلبها الموظف من حسابه.</p><div className="flex flex-wrap gap-3 text-xs"><span>مقبولة: {report.mail.counts.accepted}</span><span>فشل: {report.mail.counts.failed}</span><span>غير مؤكدة: {report.mail.counts.pending}</span></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-xs text-right"><thead><tr>{['الموظف / البريد','النوع','الحالة / الوقت','الإجراء'].map(h=><th key={h} className="p-2 bg-slate-50">{h}</th>)}</tr></thead><tbody>{report.mail.items.map((item:any)=><tr key={item.kind+item.empId} className="border-t"><td className="p-2">{item.name}<p dir="ltr" className="text-right text-slate-500">{item.email}</p></td><td className="p-2">{item.kind==='welcome'?'ترحيب':'رمز تأكيد'}</td><td className="p-2">{statusLabel[item.status]}<p className="text-slate-500">{time(item.at)}</p></td><td className="p-2">{item.canRetry?<button disabled={!!action || loading} onClick={()=>run('/api/employees/'+encodeURIComponent(item.empId)+'/welcome-email','قبلت خدمة البريد إعادة محاولة رسالة الترحيب')} className="border rounded px-3 py-2 disabled:opacity-50">إعادة المحاولة</button>:<span className="text-slate-500">{item.retryReason}</span>}</td></tr>)}</tbody></table></div>{!report.mail.items.length && <p className="text-xs text-slate-500">لا توجد حالات إرسال مسجلة لهذه الشركة.</p>}<p className="text-xs text-slate-500">عرض أحدث 100 حالة من {report.mail.total}.</p></section>
      <section className="bg-white border rounded-xl p-4 space-y-3"><h3 className="font-bold text-sm">أخطاء التشغيل الأخيرة للشركة</h3><p className="text-xs text-slate-500">تُسجل استجابات API الفاشلة منذ هذا التحديث، دون محتوى الطلبات أو بيانات الدخول. يعرض آخر 20 حالة من سجل محدود.</p>{report.errors.map((e:any,i:number)=><div key={e.at+i} className="border rounded-lg p-2 text-xs flex flex-wrap justify-between gap-2"><span dir="ltr">{e.method} {e.route} · {e.status}</span><span>{time(e.at)}</span></div>)}{!report.errors.length && <p className="text-xs text-slate-500">لا توجد أخطاء مسجلة في السجل الحالي.</p>}</section>
    </>}
  </div>;
}
